(function(){
  const API_BASE="https://educashpro-all.onrender.com";
  const platform=window.EduCashProPlatform;
  const auth=window.EduCashProWebAuth;
  if(!platform?.isWeb?.()||!auth)return;

  let overview=null;
  let busy=false;

  const COPY={
    pt:{button:"Minha conta",title:"Central EduCashPro",subtitle:"As mesmas funções da sua conta, no celular ou computador.",home:"Abrir EduCashPro",learn:"Aprender",publish:"Cadastrar projeto",affiliate:"Indicar EduCashPro",network:"Minha Rede",subscription:"Assinatura",language:"Idioma",settings:"Configurações",support:"Suporte",agenda:"Agenda Profissional",admin:"Admin",close:"Fechar",loading:"Carregando…",active:"Ativa",inactive:"Não ativa",validUntil:"Válida até",wallet:"Carteira",telegram:"Telegram",linked:"Vinculado",notLinked:"Não vinculado",devices:"Conectar outro dispositivo",approve:"Autorizar dispositivo",code:"Código de 6 dígitos",networkTitle:"Minha Rede",directs:"Diretos ativos",unlocked:"Nível liberado",level:"Nível",next:"Próximo objetivo",missing:"Faltam {n} diretos ativos para liberar o Nível {l}.",allUnlocked:"Todos os 5 níveis estão liberados.",languageTitle:"Escolha o idioma",languageSaved:"Idioma atualizado.",settingsTitle:"Configurações da conta",linkTelegram:"Vincular Telegram",adminTitle:"Administração",total:"Usuários",activeUsers:"Ativos",inactiveUsers:"Inativos",readOnly:"Painel de consulta. Nenhuma função de pagamento ou ativação é executada aqui.",error:"Não foi possível carregar agora.",authorized:"Dispositivo autorizado.",invalidCode:"Código inválido ou expirado.",webOnly:"Esta função comercial é gerenciada no site independente do EduCashPro."},
    en:{button:"My account",title:"EduCashPro Center",subtitle:"The same account features on mobile or desktop.",home:"Open EduCashPro",learn:"Learn",publish:"Submit project",affiliate:"Refer EduCashPro",network:"My Network",subscription:"Subscription",language:"Language",settings:"Settings",support:"Support",agenda:"Professional Schedule",admin:"Admin",close:"Close",loading:"Loading…",active:"Active",inactive:"Inactive",validUntil:"Valid until",wallet:"Wallet",telegram:"Telegram",linked:"Linked",notLinked:"Not linked",devices:"Connect another device",approve:"Authorize device",code:"6-digit code",networkTitle:"My Network",directs:"Active direct referrals",unlocked:"Unlocked level",level:"Level",next:"Next goal",missing:"You need {n} more active direct referrals to unlock Level {l}.",allUnlocked:"All 5 levels are unlocked.",languageTitle:"Choose language",languageSaved:"Language updated.",settingsTitle:"Account settings",linkTelegram:"Link Telegram",adminTitle:"Administration",total:"Users",activeUsers:"Active",inactiveUsers:"Inactive",readOnly:"Read-only dashboard. No payment or subscription activation runs here.",error:"Could not load right now.",authorized:"Device authorized.",invalidCode:"Invalid or expired code.",webOnly:"This commercial feature is managed on the independent EduCashPro website."},
    es:{button:"Mi cuenta",title:"Central EduCashPro",subtitle:"Las mismas funciones de tu cuenta en móvil u ordenador.",home:"Abrir EduCashPro",learn:"Aprender",publish:"Registrar proyecto",affiliate:"Indicar EduCashPro",network:"Mi Red",subscription:"Suscripción",language:"Idioma",settings:"Configuración",support:"Soporte",agenda:"Agenda Profesional",admin:"Admin",close:"Cerrar",loading:"Cargando…",active:"Activa",inactive:"No activa",validUntil:"Válida hasta",wallet:"Cartera",telegram:"Telegram",linked:"Vinculado",notLinked:"No vinculado",devices:"Conectar otro dispositivo",approve:"Autorizar dispositivo",code:"Código de 6 dígitos",networkTitle:"Mi Red",directs:"Directos activos",unlocked:"Nivel liberado",level:"Nivel",next:"Próximo objetivo",missing:"Faltan {n} directos activos para liberar el Nivel {l}.",allUnlocked:"Los 5 niveles están liberados.",languageTitle:"Elige el idioma",languageSaved:"Idioma actualizado.",settingsTitle:"Configuración de la cuenta",linkTelegram:"Vincular Telegram",adminTitle:"Administración",total:"Usuarios",activeUsers:"Activos",inactiveUsers:"Inactivos",readOnly:"Panel de consulta. Aquí no se ejecutan pagos ni activaciones.",error:"No se pudo cargar ahora.",authorized:"Dispositivo autorizado.",invalidCode:"Código inválido o caducado.",webOnly:"Esta función comercial se gestiona en el sitio independiente de EduCashPro."},
    ru:{button:"Мой аккаунт",title:"Центр EduCashPro",subtitle:"Один и тот же аккаунт на телефоне и компьютере.",home:"Открыть EduCashPro",learn:"Обучение",publish:"Добавить проект",affiliate:"Пригласить в EduCashPro",network:"Моя сеть",subscription:"Подписка",language:"Язык",settings:"Настройки",support:"Поддержка",agenda:"Расписание",admin:"Админ",close:"Закрыть",loading:"Загрузка…",active:"Активна",inactive:"Неактивна",validUntil:"Действует до",wallet:"Кошелёк",telegram:"Telegram",linked:"Привязан",notLinked:"Не привязан",devices:"Подключить другое устройство",approve:"Разрешить устройство",code:"6-значный код",networkTitle:"Моя сеть",directs:"Активные прямые",unlocked:"Открытый уровень",level:"Уровень",next:"Следующая цель",missing:"Нужно ещё {n} активных прямых для открытия уровня {l}.",allUnlocked:"Все 5 уровней открыты.",languageTitle:"Выберите язык",languageSaved:"Язык обновлён.",settingsTitle:"Настройки аккаунта",linkTelegram:"Привязать Telegram",adminTitle:"Администрирование",total:"Пользователи",activeUsers:"Активные",inactiveUsers:"Неактивные",readOnly:"Панель только для просмотра. Платежи и активации здесь не выполняются.",error:"Сейчас не удалось загрузить.",authorized:"Устройство разрешено.",invalidCode:"Код недействителен или истёк.",webOnly:"Коммерческая функция управляется на независимом сайте EduCashPro."}
  };

  function session(){return platform.readWebSession?.()||null}
  function lang(){const raw=String(session()?.profile?.language||navigator.language||"pt").toLowerCase();if(raw.startsWith("en"))return"en";if(raw.startsWith("es"))return"es";if(raw.startsWith("ru"))return"ru";return"pt"}
  function t(k){return COPY[lang()]?.[k]||COPY.pt[k]||k}
  function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
  function formatDate(sec){if(!Number(sec))return"—";try{return new Intl.DateTimeFormat(lang()==="pt"?"pt-BR":lang(),{dateStyle:"medium"}).format(new Date(Number(sec)*1000))}catch{return new Date(Number(sec)*1000).toLocaleDateString()}}
  function replaceVars(text,vars){let out=text;Object.entries(vars).forEach(([k,v])=>{out=out.replaceAll(`{${k}}`,String(v))});return out}

  async function api(path,body={}){
    const token=session()?.token;if(!token)throw new Error("session_missing");
    const response=await fetch(`${API_BASE}${path}`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(body),cache:"no-store"});
    const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data?.reason||`HTTP_${response.status}`);return data;
  }

  function styles(){if(document.getElementById("accountCenterStyles"))return;const s=document.createElement("style");s.id="accountCenterStyles";s.textContent=`
    .accountCenterBtn{min-width:42px;height:42px;border:1px solid rgba(255,255,255,.1);border-radius:13px;background:#102238;color:#fff;font-size:20px;cursor:pointer}.accountCenterLayer{position:fixed;z-index:12000;inset:0;background:rgba(1,7,15,.72);backdrop-filter:blur(8px);display:grid;place-items:end center;padding:14px}.accountCenterSheet{width:min(100%,620px);max-height:88vh;overflow:auto;background:#0d1b2d;border:1px solid rgba(255,255,255,.1);border-radius:24px 24px 18px 18px;padding:18px;color:#f7fbff;box-shadow:0 25px 80px rgba(0,0,0,.5)}.accountCenterHead{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.accountCenterHead h2{margin:0;font-size:25px}.accountCenterHead p{margin:5px 0 0;color:#9db0c6}.accountCenterClose{border:0;background:transparent;color:#9db0c6;font-size:25px;cursor:pointer}.accountCenterGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:16px}.accountAction{min-height:92px;padding:14px;border:1px solid rgba(255,255,255,.09);border-radius:17px;background:#12243b;color:#f7fbff;text-align:left;cursor:pointer}.accountAction span{font-size:24px}.accountAction b{display:block;margin-top:7px;font-size:14px}.accountAction.admin{border-color:rgba(48,230,166,.35)}.accountPanel{margin-top:14px;padding:16px;border-radius:18px;background:#102238}.accountPanel h3{margin:0 0 12px}.accountMetricGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.accountMetric{padding:12px;border-radius:13px;background:#081827}.accountMetric small{display:block;color:#9db0c6;margin-bottom:5px}.accountMetric b{font-size:17px}.accountLevel{display:flex;justify-content:space-between;gap:10px;padding:10px 0;border-bottom:1px solid rgba(255,255,255,.07)}.accountLevel:last-child{border-bottom:0}.accountPrimary{width:100%;min-height:46px;border:0;border-radius:13px;background:#30e6a6;color:#061b15;font-weight:900;cursor:pointer}.accountSecondary{width:100%;min-height:44px;margin-top:8px;border:1px solid rgba(48,230,166,.25);border-radius:13px;background:transparent;color:#30e6a6;font-weight:800;cursor:pointer}.accountField{width:100%;box-sizing:border-box;min-height:44px;padding:0 12px;border:1px solid rgba(255,255,255,.12);border-radius:12px;background:#081827;color:#fff}.accountLangGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.accountLangGrid button{min-height:45px;border:1px solid rgba(255,255,255,.1);border-radius:12px;background:#12243b;color:#fff;font-weight:800}.accountNote{color:#9db0c6;line-height:1.45;font-size:13px}.accountStatus{min-height:18px;margin-top:8px;color:#30e6a6;font-size:13px}@media(max-width:430px){.accountCenterGrid{grid-template-columns:1fr 1fr}.accountCenterSheet{max-height:91vh;padding:16px}}
  `;document.head.appendChild(s)}

  function close(){document.querySelector(".accountCenterLayer")?.remove()}
  function shell(inner=""){styles();close();const layer=document.createElement("div");layer.className="accountCenterLayer";layer.innerHTML=`<section class="accountCenterSheet"><div class="accountCenterHead"><div><h2>${esc(t("title"))}</h2><p>${esc(t("subtitle"))}</p></div><button class="accountCenterClose" type="button" aria-label="${esc(t("close"))}">✕</button></div><div id="accountCenterBody">${inner}</div></section>`;document.body.appendChild(layer);layer.querySelector(".accountCenterClose").onclick=close;layer.addEventListener("click",e=>{if(e.target===layer)close()});return layer.querySelector("#accountCenterBody")}

  function nav(view){close();const button=document.querySelector(`#bottomNav [data-view="${view}"]`);if(button){button.click();return}location.assign("./index.html")}
  function page(url){close();location.assign(url)}

  async function loadOverview(force=false){if(overview&&!force)return overview;overview=await api("/api/platform-account/overview");return overview}

  async function openNetwork(){const body=shell(`<div class="accountPanel">${esc(t("loading"))}</div>`);try{const data=await api("/api/platform-account/network");const n=data.network||{};const rows=[1,2,3,4,5].map(level=>`<div class="accountLevel"><span>${esc(t("level"))} ${level}</span><b>${Number(n.levels?.[level]||0)}</b></div>`).join("");const goal=n.allUnlocked?t("allUnlocked"):replaceVars(t("missing"),{n:n.missingDirects||0,l:n.nextLevel||"—"});body.innerHTML=`<div class="accountPanel"><h3>📊 ${esc(t("networkTitle"))}</h3><div class="accountMetricGrid"><div class="accountMetric"><small>${esc(t("directs"))}</small><b>${Number(n.directsActive||0)}</b></div><div class="accountMetric"><small>${esc(t("unlocked"))}</small><b>${Number(n.unlockedDepth||1)}</b></div></div><div style="margin-top:12px">${rows}</div><p class="accountNote"><b>${esc(t("next"))}:</b> ${esc(goal)}</p></div>`}catch{body.innerHTML=`<div class="accountPanel">${esc(t("error"))}</div>`}}

  async function openSubscription(){const body=shell(`<div class="accountPanel">${esc(t("loading"))}</div>`);try{const data=await loadOverview(true);const sub=data.subscription||{};body.innerHTML=`<div class="accountPanel"><h3>💳 ${esc(t("subscription"))}</h3><div class="accountMetricGrid"><div class="accountMetric"><small>Status</small><b>${esc(sub.active?t("active"):t("inactive"))}</b></div><div class="accountMetric"><small>${esc(t("validUntil"))}</small><b>${esc(formatDate(sub.activeUntil))}</b></div></div><p class="accountNote">${esc(t("readOnly"))}</p></div>`}catch{body.innerHTML=`<div class="accountPanel">${esc(t("error"))}</div>`}}

  async function openLanguage(){const body=shell(`<div class="accountPanel"><h3>🌐 ${esc(t("languageTitle"))}</h3><div class="accountLangGrid"><button data-lang="pt">🇧🇷 Português</button><button data-lang="en">🇺🇸 English</button><button data-lang="es">🇪🇸 Español</button><button data-lang="ru">🇷🇺 Русский</button></div><div id="accountLangStatus" class="accountStatus"></div></div>`);body.querySelectorAll("[data-lang]").forEach(btn=>btn.onclick=async()=>{if(busy)return;busy=true;try{const code=btn.dataset.lang;await api("/api/platform-account/language",{language:code});const current=session();if(current?.profile){current.profile.language=code;platform.writeWebSession(current)}document.getElementById("accountLangStatus").textContent=t("languageSaved");setTimeout(()=>location.reload(),400)}catch{document.getElementById("accountLangStatus").textContent=t("error")}finally{busy=false}})}

  async function linkTelegram(){try{const data=await api("/api/platform-auth/telegram-link/start");if(data?.telegramUrl)location.href=data.telegramUrl}catch{}}

  async function openSettings(){const body=shell(`<div class="accountPanel">${esc(t("loading"))}</div>`);try{const data=await loadOverview(true);const a=data.account||{};body.innerHTML=`<div class="accountPanel"><h3>⚙️ ${esc(t("settingsTitle"))}</h3><div class="accountMetricGrid"><div class="accountMetric"><small>${esc(t("wallet"))}</small><b>${esc(a.walletLinked?t("linked"):t("notLinked"))}</b></div><div class="accountMetric"><small>${esc(t("telegram"))}</small><b>${esc(a.telegramLinked?t("linked"):t("notLinked"))}</b></div></div>${!a.telegramLinked?`<button id="accountLinkTelegram" class="accountSecondary" type="button">✈️ ${esc(t("linkTelegram"))}</button>`:""}<div style="margin-top:14px"><input id="accountPairCode" class="accountField" inputmode="numeric" maxlength="6" placeholder="${esc(t("code"))}"><button id="accountPairApprove" class="accountPrimary" style="margin-top:8px" type="button">${esc(t("approve"))}</button><div id="accountPairStatus" class="accountStatus"></div></div></div>`;body.querySelector("#accountLinkTelegram")?.addEventListener("click",linkTelegram);body.querySelector("#accountPairApprove")?.addEventListener("click",async()=>{const input=body.querySelector("#accountPairCode");const status=body.querySelector("#accountPairStatus");const code=String(input?.value||"").replace(/\D/g,"").slice(0,6);if(code.length!==6){status.textContent=t("invalidCode");return}try{await auth.approveDevicePairing(code);status.textContent=t("authorized");input.value=""}catch{status.textContent=t("invalidCode")}})}catch{body.innerHTML=`<div class="accountPanel">${esc(t("error"))}</div>`}}

  async function openAdmin(){const body=shell(`<div class="accountPanel">${esc(t("loading"))}</div>`);try{const data=await loadOverview(true);if(!data.permissions?.admin){body.innerHTML=`<div class="accountPanel">${esc(t("error"))}</div>`;return}const s=data.adminStats||{};body.innerHTML=`<div class="accountPanel"><h3>⚙️ ${esc(t("adminTitle"))}</h3><div class="accountMetricGrid"><div class="accountMetric"><small>${esc(t("total"))}</small><b>${Number(s.total||0)}</b></div><div class="accountMetric"><small>${esc(t("activeUsers"))}</small><b>${Number(s.active||0)}</b></div><div class="accountMetric"><small>${esc(t("inactiveUsers"))}</small><b>${Number(s.inactive||0)}</b></div></div><p class="accountNote">${esc(t("readOnly"))}</p></div>`}catch{body.innerHTML=`<div class="accountPanel">${esc(t("error"))}</div>`}}

  async function open(){const body=shell(`<div class="accountPanel">${esc(t("loading"))}</div>`);let data=null;try{data=await loadOverview(true)}catch{}const admin=Boolean(data?.permissions?.admin);body.innerHTML=`<div class="accountCenterGrid"><button class="accountAction" data-action="home"><span>✨</span><b>${esc(t("home"))}</b></button><button class="accountAction" data-action="learn"><span>📚</span><b>${esc(t("learn"))}</b></button><button class="accountAction" data-action="publish"><span>🚀</span><b>${esc(t("publish"))}</b></button><button class="accountAction" data-action="affiliate"><span>💰</span><b>${esc(t("affiliate"))}</b></button><button class="accountAction" data-action="network"><span>📊</span><b>${esc(t("network"))}</b></button><button class="accountAction" data-action="subscription"><span>💳</span><b>${esc(t("subscription"))}</b></button><button class="accountAction" data-action="language"><span>🌐</span><b>${esc(t("language"))}</b></button><button class="accountAction" data-action="settings"><span>⚙️</span><b>${esc(t("settings"))}</b></button><button class="accountAction" data-action="agenda"><span>📅</span><b>${esc(t("agenda"))}</b></button><button class="accountAction" data-action="support"><span>🆘</span><b>${esc(t("support"))}</b></button>${admin?`<button class="accountAction admin" data-action="admin"><span>🛠️</span><b>${esc(t("admin"))}</b></button>`:""}</div>`;body.querySelectorAll("[data-action]").forEach(btn=>btn.onclick=()=>{switch(btn.dataset.action){case"home":nav("home");break;case"learn":nav("learn");break;case"publish":page("./publish.html");break;case"affiliate":page("./affiliate.html");break;case"network":openNetwork();break;case"subscription":openSubscription();break;case"language":openLanguage();break;case"settings":openSettings();break;case"agenda":page("./agenda.html");break;case"support":page("./support.html");break;case"admin":openAdmin();break}})}

  function install(){if(!session()?.token)return;styles();const top=document.querySelector(".topbar");if(top&&!document.getElementById("accountCenterButton")){const b=document.createElement("button");b.id="accountCenterButton";b.className="accountCenterBtn";b.type="button";b.title=t("button");b.setAttribute("aria-label",t("button"));b.textContent="👤";b.onclick=open;const closeBtn=document.getElementById("closeButton");top.insertBefore(b,closeBtn||null)}}

  const observer=new MutationObserver(install);observer.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(install,100),{once:true});else setTimeout(install,100);window.addEventListener("educashpro:web-session-ready",()=>setTimeout(install,100));window.EduCashProAccountCenter={open,openNetwork,openSubscription,openSettings,openLanguage};
})();
