const keys = [
  "title",
  "today",
  "agenda",
  "services",
  "clients",
  "team",
  "finance",
  "settings",
  "back",
  "save",
  "cancel",
  "close",
  "create",
  "activeOnly",
  "inactive",
  "newAppointment",
  "professional",
  "client",
  "service",
  "date",
  "time",
  "duration",
  "price",
  "subscriberPrice",
  "currency",
  "timezone",
  "name",
  "contact",
  "description",
  "telegram",
  "next",
  "previous",
  "profileStep",
  "servicesStep",
  "hoursStep",
  "list",
  "day",
  "week",
  "month",
  "empty",
  "search",
  "all",
  "requested",
  "confirmed",
  "attended",
  "rescheduled",
  "cancelled",
  "pending",
  "partial",
  "paid",
  "overdue",
  "amount",
  "received",
  "balance",
  "dueDate",
  "payment",
  "payments",
  "payout",
  "payouts",
  "sharePercent",
  "company",
  "professionalShare",
  "payoutDue",
  "method",
  "note",
  "adminNote",
  "privateNote",
  "password",
  "unlock",
  "noteHelp",
  "noteFailure",
  "backupNotes",
  "history",
  "edit",
  "archive",
  "archiveConfirm",
  "share",
  "copied",
  "invite",
  "inviteHelp",
  "editor",
  "viewer",
  "schedulePermission",
  "financePermission",
  "ownFinancePermission",
  "buffer",
  "notice",
  "maxDays",
  "weekly",
  "blocks",
  "start",
  "end",
  "addBlock",
  "remove",
  "noSlots",
  "selectSlot",
  "publicLead",
  "request",
  "requestSent",
  "lookup",
  "code",
  "calendar",
  "calendarHelp",
  "error",
  "invalid_amount",
  "time_unavailable",
  "outside_schedule",
  "not_allowed",
  "invalid_time",
  "ambiguous_time",
  "note_conflict",
  "owner_subscription_inactive",
  "subscribe",
  "totalServices",
  "monthReceived",
  "clientsDue",
  "monthPayouts",
  "pastDue",
  "details",
  "paidAppointments",
  "partialAppointments",
  "unpaidAppointments",
  "futurePercent",
  "splitHelp",
  "financialHelp",
  "loadMore",
  "selectAgenda",
  "acceptInvite",
  "acceptInviteHelp",
  "accepted",
  "inactiveHelp",
  "unassigned",
  "loading",
  "restoreNotes",
  "restoreHelp",
  "invalid_note",
  "restoreSuccess",
  "cancelled_payment",
  "recoveryHelp",
  "confirm",
  "invalid_range",
  "invalid_schedule",
  "invalid_currency",
  "invalid_timezone",
  "invalid_percent",
  "invalid_provider",
  "invalid_date",
  "invalid_contact",
  "invite_used",
  "invalid_invite",
  "already_member",
  "use_rescheduled",
  "ledger_limit",
  "rate_limit",
  "serviceFilter",
  "reminder",
  "terms",
  "period",
  "ledgerWarning",
  "saved",
  "setupComplete",
  "firstService",
  "notesCount",
  "attendances",
  "snapshotHelp",
];
const values = {
  pt: [
    "Agenda Profissional",
    "Hoje",
    "Agenda",
    "Serviços",
    "Clientes",
    "Equipe",
    "Financeiro",
    "Configurações",
    "Voltar",
    "Salvar",
    "Cancelar",
    "Fechar",
    "Criar minha agenda",
    "Somente assinantes ativos podem criar uma agenda. Funcionários e profissionais convidados podem ser ativos ou inativos.",
    "Novos agendamentos bloqueados",
    "Novo agendamento",
    "Profissional",
    "Cliente",
    "Serviço",
    "Data",
    "Horário",
    "Duração em minutos",
    "Preço normal",
    "Preço para assinante",
    "Moeda",
    "Fuso horário",
    "Nome",
    "Contato",
    "Descrição",
    "Contato Telegram (opcional)",
    "Continuar",
    "Anterior",
    "Perfil",
    "Serviços",
    "Horários",
    "Lista",
    "Dia",
    "Semana",
    "Mês",
    "Nenhum registro neste período.",
    "Buscar cliente ou serviço",
    "Todos",
    "Solicitado",
    "Agendado",
    "Atendido",
    "Remarcado",
    "Cancelado",
    "A receber",
    "Pago parcialmente",
    "Pago",
    "Devendo / em atraso",
    "Valor combinado",
    "Valor recebido",
    "Saldo a receber",
    "Vencimento",
    "Registrar recebimento",
    "Recebimentos",
    "Registrar repasse",
    "Repasses",
    "Percentual do profissional (%)",
    "Parte da empresa",
    "Parte do profissional",
    "Repasse pendente",
    "Forma de pagamento",
    "Observação",
    "Observação administrativa",
    "Anotação privada",
    "Senha pessoal das anotações",
    "Abrir anotação",
    "Somente você pode ler suas anotações. A senha é usada neste aparelho e não é enviada ao servidor. Use pelo menos 12 caracteres.",
    "Não foi possível abrir: confira sua senha e o arquivo.",
    "Baixar cópia das anotações",
    "Histórico",
    "Editar",
    "Arquivar",
    "Arquivar este registro? Seu histórico será preservado.",
    "Compartilhar agenda",
    "Link copiado.",
    "Gerar convite",
    "Envie o convite somente à pessoa escolhida. Ela deve entrar na própria conta. O convite vale por 7 dias.",
    "Funcionário",
    "Somente consulta",
    "Administrar agendamentos",
    "Registrar pagamentos e repasses",
    "Ver os próprios valores",
    "Intervalo entre atendimentos (min)",
    "Antecedência mínima (min)",
    "Agendar até quantos dias à frente",
    "Expediente e pausas",
    "Férias e horários bloqueados",
    "Início",
    "Fim",
    "Adicionar bloqueio",
    "Remover",
    "Nenhum horário livre. Escolha outro dia.",
    "Escolha um horário disponível",
    "Escolha o serviço, profissional, dia e horário.",
    "Solicitar agendamento",
    "Solicitação registrada. Guarde o link para consultar seu atendimento.",
    "Consultar atendimento",
    "Código ou link recebido",
    "Adicionar ao calendário",
    "O arquivo inclui lembrete 30 minutos antes. Ative os alertas no seu calendário.",
    "Não foi possível concluir. Tente novamente.",
    "Confira o valor e o saldo disponível.",
    "Este horário acabou de ser ocupado. Escolha outro.",
    "Fora do expediente, bloqueio ou antecedência permitida.",
    "Você não tem permissão para esta ação.",
    "Horário inválido no fuso escolhido.",
    "Este horário ocorre duas vezes neste fuso. Escolha um horário da lista disponível.",
    "A anotação mudou em outro aparelho. Abra novamente antes de salvar.",
    "Renove a assinatura do proprietário para receber novos agendamentos.",
    "Assinar",
    "Serviços realizados no mês",
    "Recebido no mês",
    "Saldo total dos clientes a receber",
    "Repasses efetuados no mês",
    "Saldo vencido",
    "Ver detalhes",
    "Atendidos e pagos",
    "Atendidos com pagamento parcial",
    "Atendidos não pagos",
    "Mudanças de percentual valem para novos agendamentos.",
    "O repasse é calculado sobre o valor recebido, com o percentual registrado no atendimento.",
    "Serviços: data do atendimento. Entradas: data do recebimento. Repasses: data do pagamento ao profissional. Saldos pendentes incluem todo o histórico. A parte da empresa não representa lucro. Moedas são separadas.",
    "Carregar mais",
    "Escolher agenda",
    "Aceitar convite",
    "Você entrará na equipe desta agenda com as permissões concedidas pelo proprietário.",
    "Convite aceito.",
    "Registros existentes continuam disponíveis. Novos agendamentos exigem assinatura ativa do proprietário.",
    "Atendimento do proprietário",
    "Carregando…",
    "Restaurar cópia das anotações",
    "A cópia é criptografada. Somente arquivos da sua conta podem ser restaurados; registros já existentes são preservados.",
    "Anotação ou arquivo inválido.",
    "Cópia restaurada.",
    "Atendimento cancelado: não é possível lançar novos pagamentos ou repasses.",
    "Guarde sua senha em local seguro fora do sistema e baixe uma cópia. A clínica e o EduCashPro não conseguem recuperar uma senha perdida.",
    "Confirmar",
    "Período inválido.",
    "Confira os horários, pausas e bloqueios.",
    "Moeda inválida.",
    "Fuso horário inválido.",
    "Percentual deve ficar entre 0 e 100.",
    "Profissional indisponível.",
    "Data inválida.",
    "Informe um usuário Telegram válido ou deixe vazio.",
    "Convite já utilizado.",
    "Convite inválido ou vencido.",
    "Esta pessoa já faz parte da equipe.",
    "Para mudar a data, selecione Remarcado.",
    "Limite de registros financeiros neste atendimento atingido.",
    "Aguarde um minuto antes de tentar novamente.",
    "Filtrar serviço",
    "Lembrete do atendimento",
    "Condições",
    "Período",
    "Recebimentos e repasses registrados não são apagados. Revise os dados antes de salvar.",
    "Salvo.",
    "Agenda configurada.",
    "Cadastre o primeiro serviço",
    "Anotações na cópia",
    "Atendimentos realizados",
    "Profissional, serviço, moeda, valor e percentual são preservados após o agendamento. Para corrigir, cancele e crie um novo atendimento.",
  ],
  en: [
    "Professional Agenda",
    "Today",
    "Agenda",
    "Services",
    "Customers",
    "Team",
    "Finance",
    "Settings",
    "Back",
    "Save",
    "Cancel",
    "Close",
    "Create my agenda",
    "Only active subscribers can create an agenda. Invited employees and professionals may have active or inactive subscriptions.",
    "New bookings blocked",
    "New appointment",
    "Professional",
    "Customer",
    "Service",
    "Date",
    "Time",
    "Duration in minutes",
    "Regular price",
    "Subscriber price",
    "Currency",
    "Time zone",
    "Name",
    "Contact",
    "Description",
    "Telegram contact (optional)",
    "Continue",
    "Previous",
    "Profile",
    "Services",
    "Hours",
    "List",
    "Day",
    "Week",
    "Month",
    "No records in this period.",
    "Search customer or service",
    "All",
    "Requested",
    "Scheduled",
    "Attended",
    "Rescheduled",
    "Cancelled",
    "Outstanding",
    "Partially paid",
    "Paid",
    "Overdue",
    "Agreed amount",
    "Received amount",
    "Outstanding balance",
    "Due date",
    "Record payment",
    "Payments",
    "Record payout",
    "Payouts",
    "Professional percentage (%)",
    "Company share",
    "Professional share",
    "Pending payout",
    "Payment method",
    "Note",
    "Administrative note",
    "Private note",
    "Personal notes password",
    "Open note",
    "Only you can read your notes. Your password is used on this device and is never sent to the server. Use at least 12 characters.",
    "Unable to open: check your password and file.",
    "Download notes backup",
    "History",
    "Edit",
    "Archive",
    "Archive this record? Its history will be preserved.",
    "Share agenda",
    "Link copied.",
    "Generate invitation",
    "Send the invitation only to your chosen person. They must sign in to their own account. It expires in 7 days.",
    "Employee",
    "Read only",
    "Manage appointments",
    "Record payments and payouts",
    "View own earnings",
    "Time between appointments (min)",
    "Minimum notice (min)",
    "Maximum booking days ahead",
    "Working hours and breaks",
    "Holidays and blocked times",
    "Start",
    "End",
    "Add blocked time",
    "Remove",
    "No available times. Choose another day.",
    "Choose an available time",
    "Choose a service, professional, day and time.",
    "Request appointment",
    "Request saved. Keep the link to check your appointment.",
    "Check appointment",
    "Code or received link",
    "Add to calendar",
    "The file includes a reminder 30 minutes before. Enable alerts in your calendar.",
    "Unable to complete. Please try again.",
    "Check the amount and available balance.",
    "This time was just booked. Choose another.",
    "Outside working hours, blocked time or booking notice.",
    "You do not have permission for this action.",
    "Invalid time in this time zone.",
    "This local time occurs twice. Choose an available time from the list.",
    "This note changed on another device. Open it again before saving.",
    "Renew the owner subscription to accept new bookings.",
    "Subscribe",
    "Services delivered this month",
    "Received this month",
    "Total outstanding customer balance",
    "Payouts made this month",
    "Overdue balance",
    "View details",
    "Attended and paid",
    "Attended, partially paid",
    "Attended, unpaid",
    "Percentage changes apply to new appointments.",
    "Payouts use the amount received and the percentage saved in the appointment.",
    "Services use the appointment date; receipts use the payment date; payouts use their date. Pending balances include all history. Company share is not profit. Currencies are separate.",
    "Load more",
    "Select agenda",
    "Accept invitation",
    "Join this agenda with the permissions granted by its owner.",
    "Invitation accepted.",
    "Existing records remain available. New appointments require an active owner subscription.",
    "Owner appointment",
    "Loading…",
    "Restore notes backup",
    "The backup is encrypted. Only files for your account can be restored; existing records are preserved.",
    "Invalid note or file.",
    "Backup restored.",
    "Cancelled appointment: new payments or payouts cannot be recorded.",
    "Keep your password safely outside the system and download a backup. The clinic and EduCashPro cannot recover a lost password.",
    "Confirm",
    "Invalid period.",
    "Check working hours, breaks and blocked times.",
    "Invalid currency.",
    "Invalid time zone.",
    "Percentage must be between 0 and 100.",
    "Professional unavailable.",
    "Invalid date.",
    "Enter a valid Telegram username or leave blank.",
    "Invitation already used.",
    "Invalid or expired invitation.",
    "This person is already in the team.",
    "Select Rescheduled to change the date.",
    "This appointment reached its financial record limit.",
    "Wait one minute before trying again.",
    "Filter service",
    "Appointment reminder",
    "Terms",
    "Period",
    "Recorded receipts and payouts are not deleted. Review before saving.",
    "Saved.",
    "Agenda configured.",
    "Add your first service",
    "Notes in backup",
    "Appointments attended",
    "Professional, service, currency, amount and percentage are preserved after booking. To correct them, cancel and create a new appointment.",
  ],
  es: [
    "Agenda Profesional",
    "Hoy",
    "Agenda",
    "Servicios",
    "Clientes",
    "Equipo",
    "Finanzas",
    "Configuración",
    "Volver",
    "Guardar",
    "Cancelar",
    "Cerrar",
    "Crear mi agenda",
    "Solo suscriptores activos pueden crear una agenda. Empleados y profesionales invitados pueden estar activos o inactivos.",
    "Nuevas reservas bloqueadas",
    "Nueva cita",
    "Profesional",
    "Cliente",
    "Servicio",
    "Fecha",
    "Hora",
    "Duración en minutos",
    "Precio normal",
    "Precio para suscriptor",
    "Moneda",
    "Zona horaria",
    "Nombre",
    "Contacto",
    "Descripción",
    "Contacto Telegram (opcional)",
    "Continuar",
    "Anterior",
    "Perfil",
    "Servicios",
    "Horarios",
    "Lista",
    "Día",
    "Semana",
    "Mes",
    "No hay registros en este período.",
    "Buscar cliente o servicio",
    "Todos",
    "Solicitado",
    "Agendado",
    "Atendido",
    "Reprogramado",
    "Cancelado",
    "Por cobrar",
    "Pagado parcialmente",
    "Pagado",
    "Vencido",
    "Importe acordado",
    "Importe recibido",
    "Saldo por cobrar",
    "Vencimiento",
    "Registrar cobro",
    "Cobros",
    "Registrar pago al profesional",
    "Pagos a profesionales",
    "Porcentaje del profesional (%)",
    "Parte de la empresa",
    "Parte del profesional",
    "Pago pendiente al profesional",
    "Forma de pago",
    "Observación",
    "Observación administrativa",
    "Nota privada",
    "Contraseña personal de notas",
    "Abrir nota",
    "Solo tú puedes leer tus notas. Tu contraseña se usa en este dispositivo y no se envía al servidor. Usa al menos 12 caracteres.",
    "No se pudo abrir: revisa tu contraseña y el archivo.",
    "Descargar copia de notas",
    "Historial",
    "Editar",
    "Archivar",
    "¿Archivar este registro? Su historial se conservará.",
    "Compartir agenda",
    "Enlace copiado.",
    "Generar invitación",
    "Envía la invitación solo a la persona elegida. Debe entrar en su propia cuenta. Caduca en 7 días.",
    "Empleado",
    "Solo consulta",
    "Administrar citas",
    "Registrar cobros y pagos a profesionales",
    "Ver importes propios",
    "Intervalo entre citas (min)",
    "Anticipación mínima (min)",
    "Máximo de días para reservar",
    "Horario y descansos",
    "Vacaciones y horarios bloqueados",
    "Inicio",
    "Fin",
    "Añadir bloqueo",
    "Eliminar",
    "No hay horarios libres. Elige otro día.",
    "Elige un horario disponible",
    "Elige servicio, profesional, día y hora.",
    "Solicitar cita",
    "Solicitud guardada. Conserva el enlace para consultar la cita.",
    "Consultar cita",
    "Código o enlace recibido",
    "Añadir al calendario",
    "Incluye un recordatorio 30 minutos antes. Activa alertas en tu calendario.",
    "No se pudo completar. Inténtalo de nuevo.",
    "Revisa el importe y el saldo disponible.",
    "Este horario acaba de reservarse. Elige otro.",
    "Fuera del horario, bloqueo o anticipación permitida.",
    "No tienes permiso para esta acción.",
    "Hora inválida en esta zona horaria.",
    "Esta hora ocurre dos veces. Elige un horario de la lista disponible.",
    "La nota cambió en otro dispositivo. Ábrela de nuevo antes de guardar.",
    "Renueva la suscripción del propietario para aceptar nuevas citas.",
    "Suscribirse",
    "Servicios realizados en el mes",
    "Cobrado en el mes",
    "Saldo total de clientes por cobrar",
    "Pagos a profesionales en el mes",
    "Saldo vencido",
    "Ver detalles",
    "Atendidos y pagados",
    "Atendidos con pago parcial",
    "Atendidos sin pago",
    "Los cambios de porcentaje se aplican a nuevas citas.",
    "Se calcula sobre el importe recibido, con el porcentaje guardado en la cita.",
    "Servicios: fecha de atención. Cobros: fecha del pago. Pagos a profesionales: fecha del pago. Saldos pendientes incluyen todo el historial. La parte de la empresa no es beneficio. Monedas separadas.",
    "Cargar más",
    "Elegir agenda",
    "Aceptar invitación",
    "Entrarás con los permisos concedidos por el propietario.",
    "Invitación aceptada.",
    "Los registros existentes siguen disponibles. Las nuevas citas requieren suscripción activa del propietario.",
    "Atención del propietario",
    "Cargando…",
    "Restaurar copia de notas",
    "La copia está cifrada. Solo se restauran archivos de tu cuenta; los registros existentes se conservan.",
    "Nota o archivo inválido.",
    "Copia restaurada.",
    "Cita cancelada: no se pueden registrar nuevos cobros o pagos.",
    "Guarda tu contraseña fuera del sistema y descarga una copia. La clínica y EduCashPro no pueden recuperar una contraseña perdida.",
    "Confirmar",
    "Período inválido.",
    "Revisa horarios, descansos y bloqueos.",
    "Moneda inválida.",
    "Zona horaria inválida.",
    "El porcentaje debe estar entre 0 y 100.",
    "Profesional no disponible.",
    "Fecha inválida.",
    "Introduce un usuario Telegram válido o deja vacío.",
    "Invitación ya utilizada.",
    "Invitación inválida o caducada.",
    "Esta persona ya pertenece al equipo.",
    "Selecciona Reprogramado para cambiar la fecha.",
    "Se alcanzó el límite de registros financieros de esta cita.",
    "Espera un minuto antes de intentarlo.",
    "Filtrar servicio",
    "Recordatorio de cita",
    "Condiciones",
    "Período",
    "Los cobros y pagos registrados no se eliminan. Revisa antes de guardar.",
    "Guardado.",
    "Agenda configurada.",
    "Añade el primer servicio",
    "Notas en la copia",
    "Atenciones realizadas",
    "Profesional, servicio, moneda, importe y porcentaje se conservan tras reservar. Para corregirlos, cancela y crea una nueva cita.",
  ],
  ru: [
    "Профессиональная запись",
    "Сегодня",
    "Расписание",
    "Услуги",
    "Клиенты",
    "Команда",
    "Финансы",
    "Настройки",
    "Назад",
    "Сохранить",
    "Отмена",
    "Закрыть",
    "Создать расписание",
    "Создать расписание могут только активные подписчики. Приглашённым сотрудникам и специалистам активная подписка не требуется.",
    "Новые записи заблокированы",
    "Новая запись",
    "Специалист",
    "Клиент",
    "Услуга",
    "Дата",
    "Время",
    "Длительность в минутах",
    "Обычная цена",
    "Цена для подписчика",
    "Валюта",
    "Часовой пояс",
    "Имя",
    "Контакт",
    "Описание",
    "Telegram (необязательно)",
    "Продолжить",
    "Назад",
    "Профиль",
    "Услуги",
    "Часы работы",
    "Список",
    "День",
    "Неделя",
    "Месяц",
    "В этом периоде записей нет.",
    "Поиск клиента или услуги",
    "Все",
    "Запрошено",
    "Запланировано",
    "Проведено",
    "Перенесено",
    "Отменено",
    "К получению",
    "Частично оплачено",
    "Оплачено",
    "Просрочено",
    "Согласованная сумма",
    "Полученная сумма",
    "Остаток к получению",
    "Срок оплаты",
    "Записать оплату",
    "Оплаты",
    "Записать выплату",
    "Выплаты",
    "Процент специалиста (%)",
    "Доля организации",
    "Доля специалиста",
    "Остаток к выплате",
    "Способ оплаты",
    "Примечание",
    "Административное примечание",
    "Личная заметка",
    "Личный пароль заметок",
    "Открыть заметку",
    "Только вы можете читать заметки. Пароль используется на устройстве и не отправляется на сервер. Минимум 12 символов.",
    "Не удалось открыть: проверьте пароль и файл.",
    "Скачать копию заметок",
    "История",
    "Изменить",
    "Архивировать",
    "Архивировать запись? История сохранится.",
    "Поделиться расписанием",
    "Ссылка скопирована.",
    "Создать приглашение",
    "Отправьте приглашение только выбранному человеку. Он должен войти в свой аккаунт. Срок действия — 7 дней.",
    "Сотрудник",
    "Только просмотр",
    "Управлять записями",
    "Вносить оплаты и выплаты",
    "Видеть свои суммы",
    "Перерыв между приёмами (мин)",
    "Минимальное время до записи (мин)",
    "На сколько дней вперёд можно записаться",
    "Часы работы и перерывы",
    "Отпуска и блокировки",
    "Начало",
    "Конец",
    "Добавить блокировку",
    "Удалить",
    "Нет свободного времени. Выберите другой день.",
    "Выберите свободное время",
    "Выберите услугу, специалиста, день и время.",
    "Запросить запись",
    "Запрос сохранён. Сохраните ссылку для просмотра записи.",
    "Проверить запись",
    "Код или полученная ссылка",
    "Добавить в календарь",
    "Файл включает напоминание за 30 минут. Включите уведомления в календаре.",
    "Не удалось завершить. Попробуйте снова.",
    "Проверьте сумму и доступный остаток.",
    "Это время уже занято. Выберите другое.",
    "Вне рабочего времени, заблокировано или слишком поздно для записи.",
    "У вас нет разрешения на это действие.",
    "Недопустимое время в этом часовом поясе.",
    "Это местное время встречается дважды. Выберите время из списка.",
    "Заметка изменена на другом устройстве. Откройте её снова перед сохранением.",
    "Продлите подписку владельца для новых записей.",
    "Подписаться",
    "Услуги за месяц",
    "Получено за месяц",
    "Общий долг клиентов",
    "Выплаты за месяц",
    "Просроченный долг",
    "Подробнее",
    "Проведено и оплачено",
    "Проведено, частичная оплата",
    "Проведено, не оплачено",
    "Изменение процента применяется к новым записям.",
    "Выплата рассчитывается из полученной суммы по проценту, сохранённому в записи.",
    "Услуги: дата приёма. Оплаты: дата получения. Выплаты: дата выплаты. Остатки включают всю историю. Доля организации не равна прибыли. Валюты раздельны.",
    "Загрузить ещё",
    "Выбрать расписание",
    "Принять приглашение",
    "Вы присоединитесь с разрешениями, выданными владельцем.",
    "Приглашение принято.",
    "Существующие записи доступны. Для новых записей нужна активная подписка владельца.",
    "Приём владельца",
    "Загрузка…",
    "Восстановить копию заметок",
    "Копия зашифрована. Можно восстановить только данные вашего аккаунта; существующие записи сохраняются.",
    "Недопустимая заметка или файл.",
    "Копия восстановлена.",
    "Запись отменена: новые оплаты и выплаты недоступны.",
    "Сохраните пароль вне системы и скачайте копию. Клиника и EduCashPro не могут восстановить потерянный пароль.",
    "Подтвердить",
    "Недопустимый период.",
    "Проверьте часы работы, перерывы и блокировки.",
    "Недопустимая валюта.",
    "Недопустимый часовой пояс.",
    "Процент должен быть от 0 до 100.",
    "Специалист недоступен.",
    "Недопустимая дата.",
    "Укажите корректное имя Telegram или оставьте пустым.",
    "Приглашение уже использовано.",
    "Приглашение недействительно или просрочено.",
    "Этот человек уже в команде.",
    "Для изменения даты выберите Перенесено.",
    "Достигнут предел финансовых записей для этого приёма.",
    "Подождите минуту и попробуйте снова.",
    "Фильтр услуг",
    "Напоминание о приёме",
    "Условия",
    "Период",
    "Внесённые оплаты и выплаты не удаляются. Проверьте данные перед сохранением.",
    "Сохранено.",
    "Расписание настроено.",
    "Добавьте первую услугу",
    "Заметок в копии",
    "Проведённые приёмы",
    "Специалист, услуга, валюта, сумма и процент сохраняются при записи. Для исправления отмените запись и создайте новую.",
  ],
};
export const COPY = Object.fromEntries(
  Object.entries(values).map(([language, strings]) => {
    if (strings.length !== keys.length)
      throw Error(
        `agenda_translation_count:${language}:${strings.length}/${keys.length}`,
      );
    return [
      language,
      Object.fromEntries(keys.map((key, i) => [key, strings[i]])),
    ];
  }),
);

const extra = {
  pt: {
    inheritSchedule: "Usar expediente da clínica",
    ownSchedule: "Expediente do profissional",
  },
  en: {
    inheritSchedule: "Use clinic working hours",
    ownSchedule: "Professional working hours",
  },
  es: {
    inheritSchedule: "Usar horario de la clínica",
    ownSchedule: "Horario del profesional",
  },
  ru: {
    inheritSchedule: "Использовать часы работы клиники",
    ownSchedule: "Часы работы специалиста",
  },
};
for (const [lang, labels] of Object.entries(extra))
  Object.assign(COPY[lang], labels);

for (const [lang, text] of Object.entries({
  pt: "Próximos atendimentos",
  en: "Upcoming appointments",
  es: "Próximas citas",
  ru: "Предстоящие приёмы",
}))
  COPY[lang].upcoming = text;
