(function () {
  "use strict";

  const base = window.EduCashProMentalGames;
  if (!base) return;

  const bridge = window.EduCashProGameBridge = window.EduCashProGameBridge || { session: null, catalogContext: {}, currentGame: null };
  const original = {
    setSession: typeof base.setSession === "function" ? base.setSession.bind(base) : null,
    bootPublic: typeof base.bootPublic === "function" ? base.bootPublic.bind(base) : null,
  };

  base.setSession = function (value) {
    bridge.session = value || null;
    original.setSession?.(value);
  };

  const TXT = {
    pt: {
      title: "Jogos e desafios", sub: "Treine raciocínio, matemática e vocabulário. As partidas rodam no seu aparelho.", back: "Voltar", play: "Jogar", tournament: "Criar torneio", raffle: "Criar rifa", history: "Meu histórico", free: "LIVRE", premium: "ASSINANTE", local: "Processamento local", subscriber: "Exclusivo para assinantes", subscriberText: "Este nível faz parte dos recursos avançados do EduCashPro. Ative sua assinatura para desbloquear e continuar.", presentation: "Ver apresentação EduCashPro", subscribe: "Assinar agora", cancel: "Agora não",
      sliding: "Quebra-cabeça Numérico", slidingSub: "Organize as peças usando o espaço vazio.", peg: "Resta Um", pegSub: "Várias formas de tabuleiro, cores e jogadas válidas.", math: "Math Space", mathSub: "Resolva a conta antes que ela alcance sua nave.", words: "Caça-Palavras", wordsSub: "Encontre palavras escondidas em diferentes direções.", cross: "Math Cross", crossSub: "Complete cruzamentos de operações matemáticas.",
      basic: "Básico", medium: "Médio", advanced: "Avançado", nerd: "Nerd", chooseLevel: "Escolha o nível", lives: "Vidas", score: "Pontos", combo: "Combo", pause: "Pausar", resume: "Continuar", quit: "Sair", gameOver: "Fim da partida", again: "Jogar novamente", record: "Recorde", sound: "Som", shoot: "Disparar", answer: "Digite a resposta", correct: "Acertou!", wrong: "Resposta incorreta", miss: "A questão passou!", historyEmpty: "Nenhuma partida sincronizada ainda.", syncNote: "Assinantes ativos podem sincronizar apenas o resumo final das partidas. Movimentos e animações não são enviados.",
      howPeg: "Salte uma peça sobre outra até um espaço vazio. A peça saltada sai do tabuleiro. Nos tabuleiros quadrados, as jogadas são horizontais ou verticais; no triangular, seguem os três eixos da malha.", remaining: "Restam", possible: "Mostrar jogadas", undo: "Desfazer", newGame: "Nova partida", perfect: "Final perfeito!", noMoves: "Não há mais jogadas.",
      english: "Inglês — 33", european: "Europeu — 37", wiegleb: "Wiegleb — 45", diamond: "Diamante — 41", triangle: "Triangular — 15",
      findAll: "Encontre todas", firstCell: "Toque na primeira e depois na última letra da palavra.", found: "Encontradas", crossHelp: "Toque em um espaço verde e escolha um número do banco. Multiplicação e divisão têm prioridade sobre soma e subtração.", check: "Conferir", solved: "Resolvido!", tryAgain: "Ainda há respostas incorretas.",
      historyTitle: "Histórico sincronizado", lastGames: "Últimas partidas"
    },
    en: {
      title: "Games and challenges", sub: "Train logic, math and vocabulary. Gameplay runs on your device.", back: "Back", play: "Play", tournament: "Create tournament", raffle: "Create raffle", history: "My history", free: "FREE", premium: "SUBSCRIBER", local: "Local processing", subscriber: "Subscribers only", subscriberText: "This level is part of EduCashPro advanced features. Activate your subscription to unlock it.", presentation: "View EduCashPro presentation", subscribe: "Subscribe now", cancel: "Not now",
      sliding: "Number Puzzle", slidingSub: "Put the tiles in order using the empty space.", peg: "Peg Solitaire", pegSub: "Multiple board shapes, colors and valid moves.", math: "Math Space", mathSub: "Solve the equation before it reaches your ship.", words: "Word Search", wordsSub: "Find hidden words in several directions.", cross: "Math Cross", crossSub: "Complete intersecting arithmetic equations.",
      basic: "Basic", medium: "Medium", advanced: "Advanced", nerd: "Nerd", chooseLevel: "Choose a level", lives: "Lives", score: "Score", combo: "Combo", pause: "Pause", resume: "Resume", quit: "Quit", gameOver: "Game over", again: "Play again", record: "Record", sound: "Sound", shoot: "Shoot", answer: "Enter the answer", correct: "Correct!", wrong: "Wrong answer", miss: "The question got through!", historyEmpty: "No synced games yet.", syncNote: "Active subscribers can sync only the final game summary. Moves and animations are never sent.",
      howPeg: "Jump one peg over another into an empty hole. The jumped peg is removed. Square boards use horizontal or vertical moves; the triangle follows its three grid axes.", remaining: "Left", possible: "Show moves", undo: "Undo", newGame: "New game", perfect: "Perfect finish!", noMoves: "No moves remain.", english: "English — 33", european: "European — 37", wiegleb: "Wiegleb — 45", diamond: "Diamond — 41", triangle: "Triangular — 15", findAll: "Find them all", firstCell: "Tap the first and then the last letter of a word.", found: "Found", crossHelp: "Tap a green blank and choose a number from the bank. Multiplication and division come before addition and subtraction.", check: "Check", solved: "Solved!", tryAgain: "Some answers are still incorrect.", historyTitle: "Synced history", lastGames: "Recent games"
    },
    es: {
      title: "Juegos y desafíos", sub: "Entrena lógica, matemáticas y vocabulario. Las partidas se ejecutan en tu dispositivo.", back: "Volver", play: "Jugar", tournament: "Crear torneo", raffle: "Crear rifa", history: "Mi historial", free: "LIBRE", premium: "SUSCRIPTOR", local: "Procesamiento local", subscriber: "Solo suscriptores", subscriberText: "Este nivel forma parte de las funciones avanzadas de EduCashPro. Activa tu suscripción para desbloquearlo.", presentation: "Ver presentación EduCashPro", subscribe: "Suscribirme ahora", cancel: "Ahora no", sliding: "Rompecabezas Numérico", slidingSub: "Ordena las piezas usando el espacio vacío.", peg: "Solitario de clavijas", pegSub: "Varias formas, colores y jugadas válidas.", math: "Math Space", mathSub: "Resuelve la operación antes de que alcance tu nave.", words: "Sopa de Letras", wordsSub: "Encuentra palabras ocultas en distintas direcciones.", cross: "Math Cross", crossSub: "Completa cruces de operaciones matemáticas.", basic: "Básico", medium: "Medio", advanced: "Avanzado", nerd: "Nerd", chooseLevel: "Elige el nivel", lives: "Vidas", score: "Puntos", combo: "Combo", pause: "Pausa", resume: "Continuar", quit: "Salir", gameOver: "Fin de partida", again: "Jugar de nuevo", record: "Récord", sound: "Sonido", shoot: "Disparar", answer: "Escribe la respuesta", correct: "¡Correcto!", wrong: "Respuesta incorrecta", miss: "¡La pregunta pasó!", historyEmpty: "Aún no hay partidas sincronizadas.", syncNote: "Los suscriptores activos pueden sincronizar solo el resumen final. Los movimientos y animaciones no se envían.", howPeg: "Salta una pieza sobre otra hasta un espacio vacío. La pieza saltada se elimina. Los tableros cuadrados usan movimientos horizontales o verticales; el triangular sigue sus tres ejes.", remaining: "Quedan", possible: "Mostrar jugadas", undo: "Deshacer", newGame: "Nueva partida", perfect: "¡Final perfecto!", noMoves: "No quedan jugadas.", english: "Inglés — 33", european: "Europeo — 37", wiegleb: "Wiegleb — 45", diamond: "Diamante — 41", triangle: "Triangular — 15", findAll: "Encuéntralas todas", firstCell: "Toca la primera y luego la última letra de la palabra.", found: "Encontradas", crossHelp: "Toca un espacio verde y elige un número del banco. Multiplicación y división tienen prioridad.", check: "Comprobar", solved: "¡Resuelto!", tryAgain: "Todavía hay respuestas incorrectas.", historyTitle: "Historial sincronizado", lastGames: "Partidas recientes"
    },
    ru: {
      title: "Игры и задания", sub: "Тренируйте логику, математику и словарный запас. Игра работает на устройстве.", back: "Назад", play: "Играть", tournament: "Создать турнир", raffle: "Создать розыгрыш", history: "Моя история", free: "СВОБОДНО", premium: "ПОДПИСКА", local: "Локальная обработка", subscriber: "Только для подписчиков", subscriberText: "Этот уровень относится к расширенным функциям EduCashPro. Активируйте подписку, чтобы открыть его.", presentation: "О презентации EduCashPro", subscribe: "Оформить подписку", cancel: "Не сейчас", sliding: "Числовая головоломка", slidingSub: "Расставьте плитки по порядку через пустую клетку.", peg: "Пег-солитер", pegSub: "Разные формы доски, цвета и допустимые ходы.", math: "Math Space", mathSub: "Решите пример до того, как он достигнет корабля.", words: "Поиск слов", wordsSub: "Найдите скрытые слова в разных направлениях.", cross: "Math Cross", crossSub: "Заполните пересекающиеся арифметические выражения.", basic: "Базовый", medium: "Средний", advanced: "Продвинутый", nerd: "Nerd", chooseLevel: "Выберите уровень", lives: "Жизни", score: "Очки", combo: "Комбо", pause: "Пауза", resume: "Продолжить", quit: "Выйти", gameOver: "Игра окончена", again: "Ещё раз", record: "Рекорд", sound: "Звук", shoot: "Выстрел", answer: "Введите ответ", correct: "Верно!", wrong: "Неверно", miss: "Пример прошёл!", historyEmpty: "Синхронизированных игр пока нет.", syncNote: "Активные подписчики синхронизируют только итог игры. Ходы и анимации не отправляются.", howPeg: "Перепрыгните одной фишкой через другую в пустую лунку. Перепрыгнутая фишка удаляется. На квадратных досках ходы горизонтальные/вертикальные, на треугольной — по трём осям.", remaining: "Осталось", possible: "Показать ходы", undo: "Отменить", newGame: "Новая игра", perfect: "Идеальный финал!", noMoves: "Ходов больше нет.", english: "Английская — 33", european: "Европейская — 37", wiegleb: "Виглеб — 45", diamond: "Ромб — 41", triangle: "Треугольная — 15", findAll: "Найдите все", firstCell: "Нажмите первую, затем последнюю букву слова.", found: "Найдено", crossHelp: "Нажмите зелёную клетку и выберите число. Умножение и деление выполняются раньше сложения и вычитания.", check: "Проверить", solved: "Решено!", tryAgain: "Есть неверные ответы.", historyTitle: "Синхронизированная история", lastGames: "Последние игры"
    }
  };

  const GAME_META = {
    "math-space": ["🚀", "math", "mathSub"],
    "peg-solitaire": ["🔵", "peg", "pegSub"],
    "sliding-puzzle": ["🔢", "sliding", "slidingSub"],
    "word-search": ["🔎", "words", "wordsSub"],
    "math-cross": ["➕", "cross", "crossSub"],
  };

  let raf = 0, timer = 0;
  const $ = (selector) => document.querySelector(selector);
  const content = () => document.getElementById("content");
  const esc = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" })[c]);
  function lang(requested) {
    const v = String(requested || bridge.session?.profile?.language || navigator.language || "pt").slice(0, 2).toLowerCase();
    return TXT[v] ? v : "pt";
  }
  function t(key, requested) { return TXT[lang(requested)][key] || TXT.pt[key] || key; }
  function active() { return bridge.session?.profile?.active === true; }
  function stopMotion() { if (raf) cancelAnimationFrame(raf); raf = 0; if (timer) clearInterval(timer); timer = 0; }
  function top() { window.scrollTo({ top: 0, behavior: "smooth" }); }
  function openUrl(url) { if (!url) return; const tg = window.Telegram?.WebApp; if (/^https:\/\/t\.me\//i.test(url) && tg?.openTelegramLink) tg.openTelegramLink(url); else if (tg?.openLink) tg.openLink(url); else window.open(url, "_blank", "noopener"); }
  function apiBase() { const supplied = String(new URL(location.href).searchParams.get("api") || "").replace(/\/+$/, ""); return /^https:\/\//i.test(supplied) ? supplied : "https://educashpro-all.onrender.com"; }
  async function api(path, body) {
    const response = await fetch(`${apiBase()}${path}`, { method: "POST", headers: { "Content-Type":"application/json" }, body: JSON.stringify({ token: bridge.session?.token || "", ...body }) });
    const data = await response.json().catch(() => ({ ok:false, reason:"invalid_response" }));
    if (!response.ok || data?.ok === false) { const error = new Error(data?.reason || `HTTP_${response.status}`); error.data = data; throw error; }
    return data;
  }
  function modal(icon, title, text, actions) {
    document.querySelector(".ecpModal")?.remove();
    const node = document.createElement("div"); node.className = "ecpModal";
    node.innerHTML = `<section class="ecpModalCard"><div class="ecpModalIcon">${icon}</div><h2>${esc(title)}</h2><p>${esc(text)}</p><div class="ecpModalActions ${actions.length === 2 ? "two" : ""}">${actions.map((a,i)=>`<button class="${a.primary ? "wideButton" : "secondaryButton"}" data-a="${i}">${esc(a.label)}</button>`).join("")}</div></section>`;
    document.body.appendChild(node); node.addEventListener("click", (e) => { if (e.target === node) node.remove(); });
    actions.forEach((a,i) => node.querySelector(`[data-a="${i}"]`)?.addEventListener("click", () => { if (a.close !== false) node.remove(); a.run?.(); }));
  }
  function paywall(level, requested) {
    modal("🔒", `${t("subscriber",requested)} — ${t(level,requested)}`, t("subscriberText",requested), [
      { label:t("presentation",requested), run:() => window.EduCashProApp?.renderPresentation?.(() => renderCatalog(bridge.catalogContext)) },
      { label:t("subscribe",requested), primary:true, run:() => openUrl(bridge.session?.subscribeUrl || bridge.session?.botUrl) },
      { label:t("cancel",requested) }
    ]);
  }
  function backButton(fn, requested) { return `<button class="textButton gameBackLocal" type="button">← ${esc(t("back",requested))}</button>`; }
  function bindBack(fn) { $(".gameBackLocal")?.addEventListener("click", () => { stopMotion(); fn(); }); }

  async function saveHistory(game, difficulty, summary) {
    if (!active() || !bridge.session?.token) return;
    try { await api("/api/games/history/save", { game, difficulty, score:summary.score, durationMs:summary.durationMs, hits:summary.hits, errors:summary.errors, bestCombo:summary.bestCombo, stage:summary.stage }); } catch {}
  }

  function catalogCard(gameId, requested) {
    const [icon, nameKey, subKey] = GAME_META[gameId];
    return `<article class="gameCardV2"><div class="gameCardArt">${icon}</div><h3>${esc(t(nameKey,requested))}</h3><p>${esc(t(subKey,requested))}</p><div class="gameBadges"><span class="gameBadge">${esc(t("free",requested))}</span><span class="gameBadge premium">${esc(t("premium",requested))}</span></div><div class="gameCardActions"><button class="gamePlayBtn" data-play="${gameId}">${esc(t("play",requested))}</button><button class="gameTournamentBtn" data-tournament="${gameId}">🏆 ${esc(t("tournament",requested))}</button></div></article>`;
  }

  function renderCatalog(options = {}) {
    stopMotion(); bridge.catalogContext = { ...bridge.catalogContext, ...options }; bridge.currentGame = null;
    const requested = lang(options.lang);
    document.getElementById("bottomNav")?.classList.add("hidden");
    content().innerHTML = `<main class="gameSuite"><div class="gameSuiteHeader"><div><span class="eyebrow">EDUCASHPRO PLAY</span><h1>🎮 ${esc(t("title",requested))}</h1><p>${esc(t("sub",requested))}</p></div>${bridge.catalogContext.back ? `<button class="textButton gameCatalogBack">← ${esc(t("back",requested))}</button>` : ""}</div><section class="gameCatalogV2">${Object.keys(GAME_META).map((id)=>catalogCard(id,requested)).join("")}</section><section class="socialActions"><button id="gameHistory" class="secondaryButton">☁️ ${esc(t("history",requested))}</button><button id="gameRaffle" class="secondaryButton">🎟️ ${esc(t("raffle",requested))}</button></section><p class="gameLocalNote">📱 ${esc(t("local",requested))} · ${esc(t("syncNote",requested))}</p></main>`;
    $(".gameCatalogBack")?.addEventListener("click", () => bridge.catalogContext.back?.());
    document.querySelectorAll("[data-play]").forEach((b) => b.addEventListener("click", () => launchGame(b.dataset.play, { lang:requested })));
    document.querySelectorAll("[data-tournament]").forEach((b) => b.addEventListener("click", () => window.EduCashProSocial?.openTournament?.(b.dataset.tournament, { lang:requested })));
    $("#gameRaffle")?.addEventListener("click", () => window.EduCashProSocial?.openRaffle?.({ lang:requested }));
    $("#gameHistory")?.addEventListener("click", () => active() ? renderHistory(requested) : paywall("advanced",requested)); top();
  }

  async function renderHistory(requested) {
    content().innerHTML = `<main class="gamePage">${backButton(renderCatalog,requested)}<section class="hero"><span class="eyebrow">CLOUD</span><h1>☁️ ${esc(t("historyTitle",requested))}</h1><p>${esc(t("syncNote",requested))}</p></section><div id="historyList" class="cardList"><div class="empty">•••</div></div></main>`; bindBack(() => renderCatalog(bridge.catalogContext));
    try {
      const data = await api("/api/games/history/list", {}), list = $("#historyList");
      if (!data.items?.length) list.innerHTML = `<div class="empty">${esc(t("historyEmpty",requested))}</div>`;
      else list.innerHTML = data.items.map((row) => `<article class="itemCard"><div class="itemTop"><div class="itemIcon">${GAME_META[row.game]?.[0] || "🎮"}</div><div><h3>${esc(t(GAME_META[row.game]?.[1] || "title",requested))}</h3><p>${esc(t(row.difficulty,requested))} · ${new Date(row.finishedAt).toLocaleDateString()}</p></div></div><div class="meta"><span class="chip">⭐ ${Number(row.score||0)}</span><span class="chip">⏱️ ${Math.round(Number(row.durationMs||0)/1000)}s</span>${row.bestCombo ? `<span class="chip">🔥 x${row.bestCombo}</span>` : ""}</div></article>`).join("");
    } catch { $("#historyList").innerHTML = `<div class="empty">${esc(t("historyEmpty",requested))}</div>`; }
  }

  function levelSelector(game, requested, onPick, options = {}) {
    const levels = ["basic","medium","advanced","nerd"];
    content().innerHTML = `<main class="gamePage">${backButton(renderCatalog,requested)}<section class="hero"><span class="eyebrow">${esc(t(GAME_META[game][1],requested))}</span><h1>${esc(t("chooseLevel",requested))}</h1><p>${esc(t(GAME_META[game][2],requested))}</p></section><section class="levelGrid">${levels.map((level,i)=>{const locked=i>1&&!active()&&!options.tournament;return `<button class="levelCard ${locked?"locked":""}" data-level="${level}">${locked?`<span class="lock">🔒</span>`:""}<strong>${esc(t(level,requested))}</strong><small>${i<2?esc(t("free",requested)):esc(t("premium",requested))}</small></button>`}).join("")}</section></main>`;
    bindBack(() => renderCatalog(bridge.catalogContext));
    document.querySelectorAll("[data-level]").forEach((b) => b.onclick = () => { const idx=levels.indexOf(b.dataset.level); if(idx>1&&!active()&&!options.tournament) return paywall(b.dataset.level,requested); onPick(b.dataset.level); }); top();
  }

  function xorshift(seed) { let s=Number(seed)>>>0||1; return () => { s^=s<<13;s>>>=0;s^=s>>>17;s>>>=0;s^=s<<5;s>>>=0;return s/4294967296; }; }
  function gcd(a,b){a=Math.abs(a);b=Math.abs(b);while(b)[a,b]=[b,a%b];return a||1}
  function frac(n,d){if(d<0){n*=-1;d*=-1}const g=gcd(n,d);n/=g;d/=g;return d===1?String(n):`${n}/${d}`}
  function mathQuestion(random,difficulty){const pick=n=>Math.floor(random()*n);if(difficulty==="basic"){const op=pick(4);if(op===0){const a=pick(11),b=pick(11);return [`${a} + ${b}`,String(a+b)]}if(op===1){const a=pick(11),b=pick(11),hi=Math.max(a,b),lo=Math.min(a,b);return [`${hi} − ${lo}`,String(hi-lo)]}if(op===2){const a=pick(11),b=pick(11);return [`${a} × ${b}`,String(a*b)]}const d=1+pick(10),q=pick(11);return [`${d*q} ÷ ${d}`,String(q)]}if(difficulty==="medium"){const op=pick(5);if(op===0){const a=10+pick(90),b=10+pick(90);return [`${a} + ${b}`,String(a+b)]}if(op===1){const a=20+pick(180),b=pick(a+1);return [`${a} − ${b}`,String(a-b)]}if(op===2){const a=2+pick(11),b=2+pick(11);return [`${a} × ${b}`,String(a*b)]}if(op===3){const d=2+pick(11),q=2+pick(15);return [`${d*q} ÷ ${d}`,String(q)]}const a=2+pick(18),b=2+pick(10),c=2+pick(9);return [`${a} + ${b} × ${c}`,String(a+b*c)]}if(difficulty==="advanced"){const a=1+pick(8),b=2+pick(8),c=1+pick(8),d=2+pick(8),op=pick(4);if(op===0)return [`${a}/${b} + ${c}/${d}`,frac(a*d+c*b,b*d)];if(op===1)return [`${a}/${b} − ${c}/${d}`,frac(a*d-c*b,b*d)];if(op===2)return [`${a}/${b} × ${c}/${d}`,frac(a*c,b*d)];return [`${a}/${b} ÷ ${c}/${d}`,frac(a*d,b*c)]}const kind=pick(5);if(kind===0){const r=2+pick(14);return [`√${r*r}`,String(r)]}if(kind===1){const a=2+pick(10),p=2+pick(2);return [`${a}${p===2?"²":"³"}`,String(a**p)]}if(kind===2){const pct=[10,20,25,50,75][pick(5)],base=4*(5+pick(21));return [`${pct}% de ${base}`,String(pct*base/100)]}if(kind===3){const x=1+pick(15),a=2+pick(6),b=pick(15),result=a*x+b;return [`${a}x + ${b} = ${result}`,String(x)]}const a=2+pick(8),b=2+pick(8);return [`${a}² + √${b*b}`,String(a*a+b)]}
  function normAnswer(v){const raw=String(v??"").trim().replace(",",".").replace(/−/g,"-");const m=raw.match(/^(-?\d+)\/(\d+)$/);return m&&Number(m[2])?frac(Number(m[1]),Number(m[2])):raw}

  function beep(type) {
    if (localStorage.getItem("ecp:game:sound") === "off") return;
    try { const Ctx=window.AudioContext||window.webkitAudioContext, ctx=beep.ctx||(beep.ctx=new Ctx()), osc=ctx.createOscillator(), gain=ctx.createGain(); osc.type="sine";osc.frequency.value=type==="ok"?720:type==="bad"?180:420;gain.gain.value=.035;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.08); } catch {}
  }

  function renderMath(level, requested, tournament) {
    stopMotion(); bridge.currentGame="math-space";
    const seed=tournament?.seed || crypto.getRandomValues(new Uint32Array(1))[0] || 1, random=xorshift(seed), start=Date.now();
    let lives=5, score=0, combo=0, bestCombo=0, hits=0, errors=0, misses=0, answer="", paused=false, question=null, qStart=0, events=[], finished=false;
    const highKey=`ecp:math:high:${level}`, maxSeconds=Number(tournament?.maxSeconds||0);
    content().innerHTML=`<main class="gamePage">${backButton(renderCatalog,requested)}<div class="gameTopline"><div><span class="eyebrow">${esc(t("math",requested))} · ${esc(t(level,requested))}</span></div><div class="gameStats"><button id="mathSound" class="gameStat">${localStorage.getItem("ecp:game:sound")==="off"?"🔇":"🔊"}</button><button id="mathPause" class="gameStat">⏸</button></div></div><section id="mathArena" class="mathArena"><div class="mathStars"></div><div class="mathHud"><span><strong id="mathScore">${score}</strong> · <span id="mathCombo">x0</span></span><span id="mathLives" class="mathLives">❤️❤️❤️❤️❤️</span></div><div id="mathQuestion" class="mathQuestion"></div><div id="mathLaser" class="mathLaser"></div><div class="mathShip">🚀</div><div class="mathControls"><div id="mathAnswer" class="mathAnswer">${esc(t("answer",requested))}</div><div class="mathKeypad">${[1,2,3,4,5,6,7,8,9,0,"/","-"].map(k=>`<button data-key="${k}">${k}</button>`).join("")}<button class="dangerKey" data-key="back">⌫</button><button class="dangerKey" data-key="clear">C</button><button class="shoot" data-key="shoot">🚀 ${esc(t("shoot",requested))}</button></div></div></section></main>`;
    bindBack(()=>{ if(tournament) window.EduCashProSocial?.returnToTournament?.(tournament.code); else renderCatalog(bridge.catalogContext); });
    const arena=$("#mathArena"), qel=$("#mathQuestion");
    function update(){ $("#mathScore").textContent=score;$("#mathCombo").textContent=`x${combo}`;$("#mathLives").textContent="❤️".repeat(Math.max(0,lives))+"♡".repeat(Math.max(0,5-lives));$("#mathAnswer").textContent=answer||t("answer",requested); }
    function next(){ if(finished)return;question=mathQuestion(random,level);qel.textContent=`${question[0]} = ?`;qStart=performance.now();qel.style.top="70px";answer="";update(); }
    function consumed(kind){ if(kind==="ok"){hits++;combo++;bestCombo=Math.max(bestCombo,combo);score+=10+Math.min(20,Math.max(0,combo-1)*2);events.push({answer:question[1]});beep("ok");const laser=$("#mathLaser");laser.classList.remove("fire");void laser.offsetWidth;laser.classList.add("fire");}else if(kind==="wrong"){errors++;combo=0;lives--;events.push({answer});beep("bad");}else{misses++;combo=0;lives--;events.push({miss:true});beep("bad");}update();if(lives<=0)return finish();setTimeout(next,kind==="ok"?180:100);}
    function frame(now){ if(finished)return;if(!paused){if(maxSeconds&&Date.now()-start>=maxSeconds*1000)return finish();const baseSpeed={basic:36,medium:48,advanced:44,nerd:50}[level]||40,speed=baseSpeed+Math.min(42,score/55),y=70+(now-qStart)*speed/1000;qel.style.top=`${y}px`;if(y>arena.clientHeight-235){consumed("miss");return;} }raf=requestAnimationFrame(frame); }
    async function finish(){if(finished)return;finished=true;stopMotion();const durationMs=Date.now()-start,record=Math.max(Number(localStorage.getItem(highKey)||0),score);localStorage.setItem(highKey,String(record));const summary={score,durationMs,hits,errors:errors+misses,bestCombo,stage:events.length};if(tournament){return window.EduCashProSocial?.submitTournamentResult?.(tournament,{score,stats:summary},{events});}await saveHistory("math-space",level,summary);content().innerHTML=`<main class="gamePage"><section class="hero"><span class="eyebrow">${esc(t("gameOver",requested))}</span><h1>⭐ ${score}</h1><p>${esc(t("record",requested))}: <b>${record}</b> · ${esc(t("combo",requested))}: x${bestCombo}</p></section><section class="socialActions"><button id="mathAgain" class="wideButton">${esc(t("again",requested))}</button><button id="mathLevels" class="secondaryButton">${esc(t("chooseLevel",requested))}</button></section></main>`;$("#mathAgain").onclick=()=>renderMath(level,requested);$("#mathLevels").onclick=()=>levelSelector("math-space",requested,l=>renderMath(l,requested));}
    document.querySelectorAll("[data-key]").forEach(b=>b.onclick=()=>{const k=b.dataset.key;if(k==="back")answer=answer.slice(0,-1);else if(k==="clear")answer="";else if(k==="shoot"){if(!answer||!question)return;if(normAnswer(answer)===normAnswer(question[1]))consumed("ok");else consumed("wrong");return;}else if(answer.length<8)answer+=k;update();});
    $("#mathSound").onclick=()=>{const off=localStorage.getItem("ecp:game:sound")==="off";localStorage.setItem("ecp:game:sound",off?"on":"off");$("#mathSound").textContent=off?"🔊":"🔇";};
    $("#mathPause").onclick=()=>{paused=!paused;$("#mathPause").textContent=paused?"▶":"⏸";if(paused){arena.insertAdjacentHTML("beforeend",`<div id="mathPauseOverlay" class="mathPauseOverlay"><h2>${esc(t("pause",requested))}</h2><button id="mathResume" class="wideButton">${esc(t("resume",requested))}</button><button id="mathQuit" class="secondaryButton">${esc(t("quit",requested))}</button></div>`);$("#mathResume").onclick=()=>$("#mathPause").click();$("#mathQuit").onclick=()=>renderCatalog(bridge.catalogContext);}else{$("#mathPauseOverlay")?.remove();qStart=performance.now();}};
    next();raf=requestAnimationFrame(frame);top();
  }

  function squareVariant(type){const coords=[];let size=7;if(type==="english"){for(let r=0;r<7;r++)for(let c=0;c<7;c++)if((r>=2&&r<=4)||(c>=2&&c<=4))coords.push([r,c]);}else if(type==="european"){[3,5,7,7,7,5,3].forEach((len,r)=>{const s=(7-len)/2;for(let c=s;c<s+len;c++)coords.push([r,c])});}else if(type==="wiegleb"){size=9;for(let r=0;r<9;r++)for(let c=0;c<9;c++)if((r>=3&&r<=5)||(c>=3&&c<=5))coords.push([r,c]);}else if(type==="diamond"){size=9;for(let r=0;r<9;r++){const len=1+2*(r<=4?r:8-r),s=(9-len)/2;for(let c=s;c<s+len;c++)coords.push([r,c])}}return{size,coords};}
  const PEGS=[
    {id:"english",key:"english",free:true,color:"#30e6a6"},{id:"european",key:"european",free:true,color:"#4a8cff"},{id:"wiegleb",key:"wiegleb",free:false,color:"#ffc85c"},{id:"diamond",key:"diamond",free:false,color:"#ff7aa8"},{id:"triangle",key:"triangle",free:false,color:"#a88cff"}
  ];
  function renderPegMenu(requested,tournament){content().innerHTML=`<main class="gamePage">${backButton(renderCatalog,requested)}<section class="hero"><span class="eyebrow">${esc(t("peg",requested))}</span><h1>🔵 ${esc(t("peg",requested))}</h1><p>${esc(t("howPeg",requested))}</p></section><section class="pegVariantGrid">${PEGS.map((v,i)=>`<button class="pegVariant" data-peg="${v.id}" style="border-color:${v.color}55"><span style="color:${v.color};font-size:25px">●</span><strong>${esc(t(v.key,requested))}${!v.free&&!active()&&!tournament?" 🔒":""}</strong><small>${v.free?esc(t("free",requested)):esc(t("premium",requested))}</small></button>`).join("")}</section></main>`;bindBack(()=>renderCatalog(bridge.catalogContext));document.querySelectorAll("[data-peg]").forEach(b=>b.onclick=()=>{const v=PEGS.find(x=>x.id===b.dataset.peg);if(!v.free&&!active()&&!tournament)return paywall("advanced",requested);renderPeg(v.id,requested,tournament)});top();}
  function renderPeg(type,requested,tournament){stopMotion();bridge.currentGame="peg-solitaire";const variant=PEGS.find(v=>v.id===type)||PEGS[0],start=Date.now(),history=[];let selected=null,cells=new Set(),pegs=new Set(),size=7;
    if(type==="triangle"){for(let r=0;r<5;r++)for(let c=0;c<=r;c++)cells.add(`${r},${c}`);pegs=new Set(cells);pegs.delete("0,0");}else{const data=squareVariant(type);size=data.size;cells=new Set(data.coords.map(([r,c])=>`${r},${c}`));pegs=new Set(cells);pegs.delete(type==="wiegleb"||type==="diamond"?"4,4":"3,3");}
    const initial=pegs.size;
    function movesFrom(from){if(!pegs.has(from))return[];const[fr,fc]=from.split(",").map(Number),dirs=type==="triangle"?[[0,2],[0,-2],[2,0],[-2,0],[2,2],[-2,-2]]:[[0,2],[0,-2],[2,0],[-2,0]];return dirs.flatMap(([dr,dc])=>{const to=`${fr+dr},${fc+dc}`,mid=`${fr+dr/2},${fc+dc/2}`;return cells.has(to)&&pegs.has(mid)&&!pegs.has(to)?[{from,middle:mid,to}]:[]});}
    function allMoves(){return [...pegs].flatMap(movesFrom)}
    function htmlBoard(){if(type==="triangle")return `<div class="pegBoard pegTriangle" style="--peg:${variant.color}">${[...cells].map(key=>{const[r,c]=key.split(",").map(Number),col=5-r+c*2;return `<button class="pegHole ${pegs.has(key)?"peg":""} ${selected===key?"selected":""}" data-hole="${key}" style="grid-row:${r+1};grid-column:${col}"></button>`}).join("")}</div>`;let out=`<div class="pegBoard" style="--peg:${variant.color};grid-template-columns:repeat(${size},38px)">`;for(let r=0;r<size;r++)for(let c=0;c<size;c++){const key=`${r},${c}`;out+=cells.has(key)?`<button class="pegHole ${pegs.has(key)?"peg":""} ${selected===key?"selected":""}" data-hole="${key}"></button>`:`<span class="pegVoid"></span>`;}return out+`</div>`;}
    function draw(){content().innerHTML=`<main class="gamePage">${backButton(renderPegMenu,requested)}<div class="gameTopline"><div><span class="eyebrow">${esc(t(variant.key,requested))}</span></div><div class="gameStats"><span class="gameStat">${esc(t("remaining",requested))}: <b>${pegs.size}</b></span><span class="gameStat">${history.length}</span></div></div><div id="pegHost">${htmlBoard()}</div><section class="socialActions"><button id="pegHint" class="secondaryButton">💡 ${esc(t("possible",requested))}</button><button id="pegUndo" class="secondaryButton" ${history.length?"":"disabled"}>↶ ${esc(t("undo",requested))}</button></section></main>`;bindBack(()=>tournament?window.EduCashProSocial?.returnToTournament?.(tournament.code):renderPegMenu(requested));document.querySelectorAll("[data-hole]").forEach(b=>b.onclick=()=>clickHole(b.dataset.hole));$("#pegUndo").onclick=undo;$("#pegHint").onclick=()=>{document.querySelectorAll(".pegHole.target").forEach(n=>n.classList.remove("target"));allMoves().forEach(m=>document.querySelector(`[data-hole="${m.to}"]`)?.classList.add("target"));};}
    function clickHole(key){if(pegs.has(key)){selected=key;draw();return}if(!selected)return;const move=movesFrom(selected).find(m=>m.to===key);if(!move){selected=null;draw();return}history.push(move);pegs.delete(move.from);pegs.delete(move.middle);pegs.add(move.to);selected=null;draw();if(!allMoves().length)finish();}
    function undo(){const move=history.pop();if(!move)return;pegs.add(move.from);pegs.add(move.middle);pegs.delete(move.to);selected=null;draw();}
    async function finish(){const remaining=pegs.size,score=(initial-remaining)*100+(remaining===1?1000:0),durationMs=Date.now()-start,summary={score,durationMs,hits:history.length,errors:remaining,bestCombo:0,stage:history.length};if(tournament)return window.EduCashProSocial?.submitTournamentResult?.(tournament,{score,stats:{remaining,moves:history.length}},{variant:type,moves:history.map(m=>({from:m.from,to:m.to}))});await saveHistory("peg-solitaire",variant.free?"basic":"advanced",summary);setTimeout(()=>modal(remaining===1?"🏆":"🔵",remaining===1?t("perfect",requested):t("noMoves",requested),`${t("remaining",requested)}: ${remaining} · ${t("score",requested)}: ${score}`,[{label:t("again",requested),primary:true,run:()=>renderPeg(type,requested)},{label:t("back",requested),run:()=>renderPegMenu(requested)}]),120);}
    draw();top();
  }

  function makeSliding(size,steps,random){const board=Array.from({length:size*size},(_,i)=>i===size*size-1?0:i+1);let blank=board.length-1,prev=-1;for(let s=0;s<steps;s++){const r=Math.floor(blank/size),c=blank%size;let opts=[];if(r>0)opts.push(blank-size);if(r<size-1)opts.push(blank+size);if(c>0)opts.push(blank-1);if(c<size-1)opts.push(blank+1);opts=opts.filter(x=>x!==prev);if(!opts.length)opts=[prev];const next=opts[Math.floor(random()*opts.length)%opts.length];board[blank]=board[next];board[next]=0;prev=blank;blank=next}return board}
  function renderSliding(requested,tournament,level="medium"){const size={basic:3,medium:4,advanced:5,nerd:5}[level]||4,random=xorshift(tournament?.seed||crypto.getRandomValues(new Uint32Array(1))[0]||1),board=makeSliding(size,size*size*12,random),initial=[...board],start=Date.now();let moves=0;function neighbors(blank){const r=Math.floor(blank/size),c=blank%size,o=[];if(r>0)o.push(blank-size);if(r<size-1)o.push(blank+size);if(c>0)o.push(blank-1);if(c<size-1)o.push(blank+1);return o}function solved(){return board.every((v,i)=>v===(i===board.length-1?0:i+1))}function draw(){content().innerHTML=`<main class="gamePage">${backButton(renderCatalog,requested)}<section class="hero"><span class="eyebrow">${esc(t("sliding",requested))} · ${size}×${size}</span><h1>🔢 ${esc(t("sliding",requested))}</h1><p>${esc(t("slidingSub",requested))}</p></section><div class="crossBoard"><div style="display:grid;grid-template-columns:repeat(${size},minmax(45px,70px));gap:5px;justify-content:center">${board.map((v,i)=>`<button data-slide="${i}" style="aspect-ratio:1;border:0;border-radius:12px;background:${v?"#fff3bd":"transparent"};font-weight:900;font-size:20px">${v||""}</button>`).join("")}</div></div><div class="gameStats"><span class="gameStat">${esc(t("score",requested))}: <b>${moves}</b></span></div></main>`;bindBack(()=>tournament?window.EduCashProSocial?.returnToTournament?.(tournament.code):renderCatalog(bridge.catalogContext));document.querySelectorAll("[data-slide]").forEach(b=>b.onclick=()=>{const i=Number(b.dataset.slide),blank=board.indexOf(0);if(!neighbors(blank).includes(i))return;board[blank]=board[i];board[i]=0;moves++;if(solved())finish();else draw();});}async function finish(){const durationMs=Date.now()-start,score=Math.max(100,10000-moves*20-Math.floor(durationMs/1000)*5),summary={score,durationMs,hits:moves,errors:0,bestCombo:0,stage:size};if(tournament)return window.EduCashProSocial?.submitTournamentResult?.(tournament,{score,stats:{moves,size}},{initial,moves});await saveHistory("sliding-puzzle",level,summary);modal("🏆",t("solved",requested),`${t("score",requested)}: ${score} · ${moves} ${t("moves",requested)||""}`,[{label:t("again",requested),primary:true,run:()=>renderSliding(requested,null,level)},{label:t("back",requested),run:()=>renderCatalog(bridge.catalogContext)}]);}draw();top();}

  const WORDS={
    pt:["PLANETA","ENERGIA","FUTURO","ESCOLA","AMIZADE","CIENCIA","DINHEIRO","VIAGEM","CULTURA","HISTORIA","NATUREZA","TECNOLOGIA"],
    en:["PLANET","ENERGY","FUTURE","SCHOOL","FRIEND","SCIENCE","MONEY","TRAVEL","CULTURE","HISTORY","NATURE","TECHNOLOGY"],
    es:["PLANETA","ENERGIA","FUTURO","ESCUELA","AMISTAD","CIENCIA","DINERO","VIAJE","CULTURA","HISTORIA","NATURALEZA","TECNOLOGIA"],
    ru:["ПЛАНЕТА","ЭНЕРГИЯ","БУДУЩЕЕ","ШКОЛА","ДРУЖБА","НАУКА","ДЕНЬГИ","ПОЕЗДКА","КУЛЬТУРА","ИСТОРИЯ","ПРИРОДА","ТЕХНОЛОГИЯ"]
  };
  function renderWordSearch(level,requested,tournament){const l=lang(requested),size={basic:8,medium:10,advanced:11,nerd:12}[level]||10,count={basic:5,medium:7,advanced:9,nerd:10}[level]||7,random=xorshift(tournament?.seed||crypto.getRandomValues(new Uint32Array(1))[0]||1),all=WORDS[l]||WORDS.pt,targets=[...all].sort(()=>random()-.5).slice(0,count).map(w=>w.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase()),grid=Array.from({length:size},()=>Array(size).fill("")),dirs=[[0,1],[1,0],[1,1],[1,-1]],positions={};const letters=l==="ru"?"АБВГДЕЖЗИКЛМНОПРСТУФХЦЧШЫЭЮЯ":"ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    targets.forEach(word=>{for(let tries=0;tries<200;tries++){const[dr,dc]=dirs[Math.floor(random()*dirs.length)],r=Math.floor(random()*size),c=Math.floor(random()*size),er=r+dr*(word.length-1),ec=c+dc*(word.length-1);if(er<0||er>=size||ec<0||ec>=size)continue;let ok=true;for(let i=0;i<word.length;i++){const cur=grid[r+dr*i][c+dc*i];if(cur&&cur!==word[i]){ok=false;break}}if(!ok)continue;positions[word]=[];for(let i=0;i<word.length;i++){grid[r+dr*i][c+dc*i]=word[i];positions[word].push(`${r+dr*i},${c+dc*i}`)}break}});for(let r=0;r<size;r++)for(let c=0;c<size;c++)if(!grid[r][c])grid[r][c]=letters[Math.floor(random()*letters.length)];let first=null,found=new Set(),start=Date.now();
    function draw(){content().innerHTML=`<main class="gamePage">${backButton(renderCatalog,requested)}<section class="hero"><span class="eyebrow">${esc(t("words",requested))} · ${esc(t(level,requested))}</span><h1>🔎 ${esc(t("findAll",requested))}</h1><p>${esc(t("firstCell",requested))}</p></section><div class="wordList">${targets.map(w=>`<span class="wordChip ${found.has(w)?"done":""}">${esc(w)}</span>`).join("")}</div><div class="wordBoard" style="grid-template-columns:repeat(${size},1fr)">${grid.flatMap((row,r)=>row.map((ch,c)=>{const key=`${r},${c}`,isFound=[...found].some(w=>positions[w]?.includes(key));return `<button class="wordCell ${first===key?"first":""} ${isFound?"found":""}" data-word-cell="${key}">${esc(ch)}</button>`})).join("")}</div><div class="gameStats"><span class="gameStat">${esc(t("found",requested))}: <b>${found.size}/${targets.length}</b></span></div></main>`;bindBack(()=>tournament?window.EduCashProSocial?.returnToTournament?.(tournament.code):levelSelector("word-search",requested,x=>renderWordSearch(x,requested)));document.querySelectorAll("[data-word-cell]").forEach(b=>b.onclick=()=>pick(b.dataset.wordCell));}
    function pick(key){if(!first){first=key;draw();return}const[a,b]=first.split(",").map(Number),[c,d]=key.split(",").map(Number),dr=c-a,dc=d-b,steps=Math.max(Math.abs(dr),Math.abs(dc));if(!(dr===0||dc===0||Math.abs(dr)===Math.abs(dc))||!steps){first=null;draw();return}const sr=dr/steps,sc=dc/steps;let word="",keys=[];for(let i=0;i<=steps;i++){word+=grid[a+sr*i]?.[b+sc*i]||"";keys.push(`${a+sr*i},${b+sc*i}`)}const rev=[...word].reverse().join(""),match=targets.find(w=>!found.has(w)&&(w===word||w===rev));if(match){found.add(match);beep("ok")}first=null;if(found.size===targets.length)finish();else draw();}
    async function finish(){const durationMs=Date.now()-start,score=targets.length*100+Math.max(0,1000-Math.floor(durationMs/1000)*5),summary={score,durationMs,hits:found.size,errors:0,bestCombo:0,stage:targets.length};if(tournament)return window.EduCashProSocial?.submitTournamentResult?.(tournament,{score,stats:{found:found.size,total:targets.length}},{found:[...found]});await saveHistory("word-search",level,summary);modal("🏆",t("solved",requested),`${t("score",requested)}: ${score}`,[{label:t("again",requested),primary:true,run:()=>renderWordSearch(level,requested)},{label:t("back",requested),run:()=>renderCatalog(bridge.catalogContext)}]);}draw();top();}

  function eval3(a,o1,b,o2,c){const apply=(x,o,y)=>o==="+"?x+y:o==="-"?x-y:o==="×"?x*y:x/y;const high=o=>o==="×"||o==="÷";if(high(o1)){const x=apply(a,o1,b);return high(o2)?apply(x,o2,c):apply(x,o2,c)}if(high(o2)){const x=apply(b,o2,c);return apply(a,o1,x)}return apply(apply(a,o1,b),o2,c)}
  function makeCross(level,random){const ops=level==="basic"?["+"]:level==="medium"?["+","-"]:level==="advanced"?["+","-","×"]:["+","-","×","÷"];for(let tries=0;tries<300;tries++){const max=level==="basic"?9:level==="medium"?15:20,m=Array.from({length:9},()=>1+Math.floor(random()*max)),ro=Array.from({length:6},()=>ops[Math.floor(random()*ops.length)]),row=[eval3(m[0],ro[0],m[1],ro[1],m[2]),eval3(m[3],ro[2],m[4],ro[3],m[5]),eval3(m[6],ro[4],m[7],ro[5],m[8])],co=[eval3(m[0],ro[0],m[3],ro[1],m[6]),eval3(m[1],ro[2],m[4],ro[3],m[7]),eval3(m[2],ro[4],m[5],ro[5],m[8])];if([...row,...co].every(Number.isInteger))return{m,ro,row,co}}return makeCross("basic",random)}
  function renderCross(level,requested,tournament){const random=xorshift(tournament?.seed||crypto.getRandomValues(new Uint32Array(1))[0]||1),p=makeCross(level,random),hideCount={basic:2,medium:3,advanced:4,nerd:5}[level],hidden=[...Array(9).keys()].sort(()=>random()-.5).slice(0,hideCount),fills={},selected=null,start=Date.now(),bank=hidden.map(i=>p.m[i]);for(let i=0;i<Math.max(2,hideCount-1);i++)bank.push(1+Math.floor(random()*20));
    function tile(value,cls=""){return `<span class="crossTile ${cls}">${esc(value)}</span>`}function draw(){let html="";for(let rr=0;rr<7;rr++)for(let cc=0;cc<7;cc++){let val="",cls="operator";const evenR=rr%2===0,evenC=cc%2===0;if(rr===0||rr===2||rr===4){const row=rr/2;if(cc===0||cc===2||cc===4){const idx=row*3+cc/2;if(hidden.includes(idx)){val=fills[idx]??"?";cls="blank";html+=`<button class="crossTile blank" data-blank="${idx}">${val}</button>`;continue}else{val=p.m[idx];cls=""}}else if(cc===1)val=p.ro[row*2];else if(cc===3)val=p.ro[row*2+1];else if(cc===5)val="=";else if(cc===6)val=p.row[row];else{html+=tile("", "operator");continue}}else if(rr===1||rr===3){if(cc===0)val=p.ro[(rr-1)/2*2];else if(cc===2)val=p.ro[(rr-1)/2*2+1];else if(cc===4)val=p.ro[(rr-1)/2*2];else{html+=tile("", "operator");continue}}else if(rr===5){if(cc===0||cc===2||cc===4)val="=";else{html+=tile("", "operator");continue}}else if(rr===6){if(cc===0)val=p.co[0];else if(cc===2)val=p.co[1];else if(cc===4)val=p.co[2];else{html+=tile("", "operator");continue}}html+=tile(val,cls)}content().innerHTML=`<main class="gamePage">${backButton(renderCatalog,requested)}<section class="hero"><span class="eyebrow">${esc(t("cross",requested))} · ${esc(t(level,requested))}</span><h1>➕ ${esc(t("cross",requested))}</h1><p>${esc(t("crossHelp",requested))}</p></section><div class="crossBoard"><div class="crossGrid">${html}</div></div><div class="crossBank">${bank.map((v,i)=>`<button data-bank="${i}" data-value="${v}">${v}</button>`).join("")}</div><button id="crossCheck" class="wideButton">${esc(t("check",requested))}</button></main>`;bindBack(()=>tournament?window.EduCashProSocial?.returnToTournament?.(tournament.code):levelSelector("math-cross",requested,x=>renderCross(x,requested)));document.querySelectorAll("[data-blank]").forEach(b=>b.onclick=()=>{selected=Number(b.dataset.blank);document.querySelectorAll("[data-blank]").forEach(x=>x.style.outline="");b.style.outline="3px solid #30e6a6"});document.querySelectorAll("[data-bank]").forEach(b=>b.onclick=()=>{if(selected===null)return;fills[selected]=Number(b.dataset.value);draw()});$("#crossCheck").onclick=check;}
    async function check(){const ok=hidden.every(i=>Number(fills[i])===p.m[i]);if(!ok)return modal("🧩",t("tryAgain",requested),t("crossHelp",requested),[{label:t("back",requested),primary:true}]);const durationMs=Date.now()-start,score=hidden.length*250+Math.max(0,1000-Math.floor(durationMs/1000)*5),summary={score,durationMs,hits:hidden.length,errors:0,bestCombo:0,stage:hidden.length};if(tournament)return window.EduCashProSocial?.submitTournamentResult?.(tournament,{score,stats:{filled:hidden.length}},{fills});await saveHistory("math-cross",level,summary);modal("🏆",t("solved",requested),`${t("score",requested)}: ${score}`,[{label:t("again",requested),primary:true,run:()=>renderCross(level,requested)},{label:t("back",requested),run:()=>renderCatalog(bridge.catalogContext)}]);}draw();top();}

  function tournamentPegVariant(level){return{basic:"english",medium:"european",advanced:"wiegleb",nerd:"triangle"}[level]||"english"}
  function launchGame(gameId, options={}){
    const requested=lang(options.lang), tournament=options.tournament||null, level=tournament?.difficulty||options.level;
    bridge.currentGame=gameId;
    if(gameId==="math-space")return level?renderMath(level,requested,tournament):levelSelector(gameId,requested,l=>renderMath(l,requested));
    if(gameId==="peg-solitaire")return tournament?renderPeg(tournamentPegVariant(level),requested,tournament):renderPegMenu(requested);
    if(gameId==="sliding-puzzle")return level?renderSliding(requested,tournament,level):levelSelector(gameId,requested,l=>renderSliding(requested,null,l));
    if(gameId==="word-search")return level?renderWordSearch(level,requested,tournament):levelSelector(gameId,requested,l=>renderWordSearch(l,requested));
    if(gameId==="math-cross")return level?renderCross(level,requested,tournament):levelSelector(gameId,requested,l=>renderCross(l,requested));
    renderCatalog(bridge.catalogContext);
  }

  const previousBoot=base.bootPublic;
  base.bootPublic=async function(params){const game=String(params?.get?.("game")||"");if(GAME_META[game]){launchGame(game,{lang:params.get("lang")});return true}return previousBoot?previousBoot(params):false};
  base.renderCatalog=renderCatalog;
  window.EduCashProGameSuite={renderCatalog,launchGame,renderHistory,paywall,text:t,api,active,lang,GAME_META};
})();
