(function(){
'use strict';
const F=window.EduCashProFinanceModel,M=window.EduCashProReceivablesModel;
function normalize(x){if(!x||typeof x!=='object')throw Error('invalid');const issuer=String(x.issuer||'').trim(),customer=String(x.customer||'').trim();if(!issuer||!customer||issuer.length>160||customer.length>160||!M.currencies.includes(x.currency||'USD'))throw Error('invalid');
if(!Array.isArray(x.items)||!x.items.length)throw Error('invalid');const items=x.items.map(p=>{const name=String(p.name||'').trim(),qty=Number(String(p.qty).replace(',','.')),price=F.parseAmount(p.price);if(!name||name.length>300||!Number.isFinite(qty)||qty<=0||qty>1e6||!Number.isFinite(price)||price<0||qty*price>1e9)throw Error('invalid');return {name,qty,price,unit:String(p.unit||'unit').slice(0,30)};});
const subtotal=items.reduce((n,p)=>n+Math.round(p.qty*p.price*100),0),discount=F.parseAmount(x.discount??0);if(!Number.isFinite(discount)||Math.round(discount*100)>subtotal)throw Error('invalid');const date=String(x.date||M.today()),validUntil=String(x.validUntil||'');if(!M.validDate(date)||(validUntil&&(!M.validDate(validUntil)||validUntil<date)))throw Error('invalid');const logo=String(x.logo||'');if(logo&&(!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(logo)||logo.length>800000))throw Error('invalid');return {id:String(x.id||M.id()),ref:String(x.ref||'').slice(0,60),issuer,customer,currency:x.currency||'USD',contact:String(x.contact||'').slice(0,500),customerContact:String(x.customerContact||'').slice(0,500),date,validUntil,items,subtotal:subtotal/100,discount,total:(subtotal-Math.round(discount*100))/100,notes:String(x.notes||'').slice(0,3000),scope:String(x.scope||'').slice(0,3000),payment:String(x.payment||'').slice(0,1000),deadline:String(x.deadline||'').slice(0,500),logo,template:['classic','services','products'].includes(x.template)?x.template:'classic',status:['draft','sent','accepted','rejected'].includes(x.status)?x.status:'draft'};}
function restore(text){const d=JSON.parse(text);if(d.type!=='educashpro-quotes'||d.version!==1||!Array.isArray(d.records))throw Error('invalid');const list=d.records.map(normalize);if(new Set(list.map(x=>x.id)).size!==list.length)throw Error('invalid');return {records:list};}
window.EduCashProQuotesModel={normalize,restore};
})();
