(function () {
  "use strict";
  const suite = () => window.EduCashProGameSuite;
  const bridge = window.EduCashProGameBridge || (window.EduCashProGameBridge = { session:null, catalogContext:{} });
  const base = window.EduCashProMentalGames;
  if (!base) return;

  let currentTournament = null, lobbyTimer = null, countdownTimer = null, selectedRaffleNumber = null;
  const $ = (s) => document.querySelector(s);
  const content = () => document.getElementById("content");
  const esc = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
  const lang = (v) => suite()?.lang?.(v) || "pt";
  const tr = (key, l) => suite()?.text?.(key,l) || key;
  const active = () => bridge.session?.profile?.active === true;
  function stopTimers(){if(lobbyTimer)clearInterval(lobbyTimer);if(countdownTimer)clearInterval(countdownTimer);lobbyTimer=countdownTimer=null;}
  function openUrl(url){if(!url)return;const tg=window.Telegram?.WebApp;if(/^https:\/\/t\.me\//i.test(url)&&tg?.openTelegramLink)tg.openTelegramLink(url);else if(tg?.openLink)tg.openLink(url);else window.open(url,"_blank","noopener");}
  async function api(path, body){return suite().api(path,body)}
  function backCatalog(){stopTimers();suite()?.renderCatalog?.(bridge.catalogContext)}
  function backButton(l, fn="catalog"){return `<button class="textButton socialBack" type="button">← ${esc(tr("back",l))}</button>`}
  function bindBack(fn=backCatalog){$(".socialBack")?.addEventListener("click",fn)}
  function copy(text,button){navigator.clipboard?.writeText(text).then(()=>{const old=button.textContent;button.textContent="✓";setTimeout(()=>button.textContent=old,1200)}).catch(()=>{});}
  function shareTelegram(url,text){openUrl(`https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(text||"")}`)}
  function qr(host,value){if(!host||!value)return;host.innerHTML="";let tries=0;const run=()=>{if(window.QRCode){new window.QRCode(host,{text:value,width:210,height:210,correctLevel:window.QRCode.CorrectLevel?.M});return}if(tries++<20)setTimeout(run,150);else host.textContent=value};run();}
  function fmtDate(value){try{return new Date(value).toLocaleString()}catch{return String(value||"")}}
  function gameName(id,l){const meta=suite()?.GAME_META?.[id];return meta?tr(meta[1],l):id}

  const COPY={
    pt:{
      strategyTitle:"Antes de criar seu torneio",strategy:"Crie primeiro um grupo exclusivo no Telegram e reúna as pessoas que deseja convidar. Depois compartilhe o link ou o QR Code do torneio dentro do grupo. Isso facilita os avisos, o horário de início e a divulgação do EduCashPro.",strategyAffiliate:"Se um convidado ainda não possuir vínculo de afiliado e o organizador continuar com assinatura ativa, o convite do torneio poderá registrar o organizador como indicador. Vínculos existentes nunca serão substituídos.",continue:"Continuar e criar torneio",groupHelp:"Dica: crie o grupo pelo próprio Telegram, adicione os convidados e fixe a mensagem pronta do torneio.",
      createTitle:"Criar torneio",name:"Nome do torneio",start:"Data e hora de início",duration:"Duração máxima",winners:"Quantidade de vencedores",difficulty:"Dificuldade",rules:"Regras adicionais (opcional)",hide:"Ocultar ranking até o final",create:"Criar torneio",creating:"Criando…",minutes:"minutos",invalid:"Revise os dados do torneio.",
      created:"Torneio criado",code:"Código",shareLink:"Link do torneio",copyLink:"Copiar link",share:"Compartilhar no Telegram",longMsg:"Copiar mensagem completa",shortMsg:"Copiar mensagem curta",openRoom:"Abrir sala do torneio",affiliateDisclosure:"Convite com indicação transparente: somente participantes ainda sem vínculo podem ser associados ao organizador; vínculos anteriores permanecem intactos.",
      join:"PARTICIPAR",joined:"Inscrição confirmada",oneChance:"Você terá apenas uma tentativa. Depois de iniciar, fechar o jogo não cria uma nova tentativa.",waiting:"Aguardando início",startsIn:"Começa em",playNow:"JOGAR AGORA",participants:"Participantes",completed:"Concluíram",refresh:"Atualizar",resultRegistered:"Resultado registrado",provisional:"Posição provisória",official:"Resultado oficial",noWinners:"Nenhum participante concluiu uma tentativa válida.",
      raffleIntro:"Criar rifa / sorteio por números",raffleExplain:"Ferramenta de organização e sorteio. O EduCashPro não recebe pagamentos, não vende números e não administra prêmios.",responsibility:"O organizador é responsável pelo objeto sorteado, condições de participação e cumprimento das regras aplicáveis em sua localidade.",raffleName:"Nome da rifa",numbers:"Quantidade de números",description:"Descrição (opcional)",drawAt:"Data prevista do sorteio (opcional)",createRaffle:"Criar rifa",activeRaffle:"Você já possui uma rifa atual. Conclua-a antes de criar outra.",available:"Disponível",taken:"Escolhido",choose:"Escolha um número",displayName:"Nome que será exibido",confirmNumber:"Confirmar número",closeEntries:"Encerrar inscrições",draw:"REALIZAR SORTEIO",winner:"Número sorteado",raffleCreated:"Rifa criada",current:"Atual",last:"Última concluída",noClaims:"Ainda não há números escolhidos.",
      groupMessageTitle:"Mensagem pronta para o grupo",owner:"Organizador",status:"Status",disclosure:"Competição organizada por um usuário do EduCashPro. O EduCashPro registra inscrições, tentativa e resultado; eventual prêmio ou compromisso é responsabilidade do organizador."
    },
    en:{strategyTitle:"Before creating your tournament",strategy:"Create a private Telegram group first and gather the people you want to invite. Then share the tournament link or QR Code in the group.",strategyAffiliate:"If a guest has no affiliate relationship yet and the organizer remains active, the tournament invite may register the organizer as referrer. Existing relationships are never replaced.",continue:"Continue and create tournament",groupHelp:"Tip: create the group in Telegram, add guests and pin the tournament message.",createTitle:"Create tournament",name:"Tournament name",start:"Start date and time",duration:"Maximum duration",winners:"Number of winners",difficulty:"Difficulty",rules:"Additional rules (optional)",hide:"Hide ranking until the end",create:"Create tournament",creating:"Creating…",minutes:"minutes",invalid:"Review tournament data.",created:"Tournament created",code:"Code",shareLink:"Tournament link",copyLink:"Copy link",share:"Share on Telegram",longMsg:"Copy full message",shortMsg:"Copy short message",openRoom:"Open tournament room",affiliateDisclosure:"Transparent referral: only guests without an existing relationship may be linked to the organizer.",join:"JOIN",joined:"Registration confirmed",oneChance:"You have one attempt only. Closing after starting does not create a new attempt.",waiting:"Waiting to start",startsIn:"Starts in",playNow:"PLAY NOW",participants:"Participants",completed:"Completed",refresh:"Refresh",resultRegistered:"Result registered",provisional:"Provisional position",official:"Official result",noWinners:"No participant completed a valid attempt.",raffleIntro:"Create number raffle",raffleExplain:"Organization and draw tool. EduCashPro does not collect payments, sell numbers or manage prizes.",responsibility:"The organizer is responsible for the prize, participation conditions and local rules.",raffleName:"Raffle name",numbers:"Number count",description:"Description (optional)",drawAt:"Planned draw date (optional)",createRaffle:"Create raffle",activeRaffle:"You already have an active raffle.",available:"Available",taken:"Taken",choose:"Choose a number",displayName:"Display name",confirmNumber:"Confirm number",closeEntries:"Close entries",draw:"DRAW NOW",winner:"Winning number",raffleCreated:"Raffle created",current:"Current",last:"Last completed",noClaims:"No numbers chosen yet.",groupMessageTitle:"Ready group message",owner:"Organizer",status:"Status",disclosure:"Competition organized by an EduCashPro user. EduCashPro records participation and results; prizes remain the organizer's responsibility."},
    es:{strategyTitle:"Antes de crear tu torneo",strategy:"Crea primero un grupo exclusivo en Telegram y reúne a las personas que quieras invitar. Luego comparte allí el enlace o QR del torneo.",strategyAffiliate:"Si un invitado todavía no tiene vínculo de afiliado y el organizador sigue activo, la invitación puede registrar al organizador como referente. Los vínculos existentes nunca se sustituyen.",continue:"Continuar y crear torneo",groupHelp:"Consejo: crea el grupo en Telegram, agrega a los invitados y fija el mensaje del torneo.",createTitle:"Crear torneo",name:"Nombre del torneo",start:"Fecha y hora de inicio",duration:"Duración máxima",winners:"Cantidad de ganadores",difficulty:"Dificultad",rules:"Reglas adicionales (opcional)",hide:"Ocultar ranking hasta el final",create:"Crear torneo",creating:"Creando…",minutes:"minutos",invalid:"Revisa los datos.",created:"Torneo creado",code:"Código",shareLink:"Enlace del torneo",copyLink:"Copiar enlace",share:"Compartir en Telegram",longMsg:"Copiar mensaje completo",shortMsg:"Copiar mensaje corto",openRoom:"Abrir sala",affiliateDisclosure:"Indicación transparente: solo invitados sin vínculo previo pueden asociarse al organizador.",join:"PARTICIPAR",joined:"Inscripción confirmada",oneChance:"Tendrás un solo intento. Cerrar el juego después de iniciar no crea otro intento.",waiting:"Esperando inicio",startsIn:"Comienza en",playNow:"JUGAR AHORA",participants:"Participantes",completed:"Completaron",refresh:"Actualizar",resultRegistered:"Resultado registrado",provisional:"Posición provisional",official:"Resultado oficial",noWinners:"Nadie completó un intento válido.",raffleIntro:"Crear rifa por números",raffleExplain:"Herramienta de organización y sorteo. EduCashPro no cobra pagos, no vende números ni administra premios.",responsibility:"El organizador es responsable del premio, condiciones y reglas aplicables.",raffleName:"Nombre de la rifa",numbers:"Cantidad de números",description:"Descripción (opcional)",drawAt:"Fecha prevista (opcional)",createRaffle:"Crear rifa",activeRaffle:"Ya tienes una rifa activa.",available:"Disponible",taken:"Elegido",choose:"Elige un número",displayName:"Nombre visible",confirmNumber:"Confirmar número",closeEntries:"Cerrar inscripciones",draw:"REALIZAR SORTEO",winner:"Número sorteado",raffleCreated:"Rifa creada",current:"Actual",last:"Última finalizada",noClaims:"Todavía no hay números elegidos.",groupMessageTitle:"Mensaje listo para el grupo",owner:"Organizador",status:"Estado",disclosure:"Competición organizada por un usuario de EduCashPro. EduCashPro registra participación y resultados; los premios son responsabilidad del organizador."},
    ru:{strategyTitle:"Перед созданием турнира",strategy:"Сначала создайте отдельную группу Telegram и соберите приглашённых. Затем разместите в группе ссылку или QR-код турнира.",strategyAffiliate:"Если у гостя ещё нет реферальной связи и организатор остаётся активным, приглашение может закрепить организатора как реферера. Существующие связи не меняются.",continue:"Продолжить и создать",groupHelp:"Совет: создайте группу в Telegram, добавьте участников и закрепите сообщение турнира.",createTitle:"Создать турнир",name:"Название турнира",start:"Дата и время начала",duration:"Максимальная длительность",winners:"Количество победителей",difficulty:"Сложность",rules:"Дополнительные правила",hide:"Скрыть рейтинг до конца",create:"Создать турнир",creating:"Создание…",minutes:"минут",invalid:"Проверьте данные.",created:"Турнир создан",code:"Код",shareLink:"Ссылка турнира",copyLink:"Копировать ссылку",share:"Поделиться в Telegram",longMsg:"Копировать полное сообщение",shortMsg:"Копировать короткое сообщение",openRoom:"Открыть комнату",affiliateDisclosure:"Прозрачная реферальная связь: только участники без прежней связи могут быть закреплены за организатором.",join:"УЧАСТВОВАТЬ",joined:"Регистрация подтверждена",oneChance:"У вас одна попытка. Закрытие игры после старта не даёт новую попытку.",waiting:"Ожидание начала",startsIn:"До начала",playNow:"ИГРАТЬ",participants:"Участники",completed:"Завершили",refresh:"Обновить",resultRegistered:"Результат зарегистрирован",provisional:"Предварительное место",official:"Официальный результат",noWinners:"Нет завершённых действительных попыток.",raffleIntro:"Создать розыгрыш по номерам",raffleExplain:"Инструмент организации и жеребьёвки. EduCashPro не принимает платежи и не управляет призами.",responsibility:"Организатор отвечает за приз, условия участия и местные правила.",raffleName:"Название",numbers:"Количество номеров",description:"Описание",drawAt:"Дата жеребьёвки",createRaffle:"Создать",activeRaffle:"У вас уже есть активный розыгрыш.",available:"Свободно",taken:"Занято",choose:"Выберите номер",displayName:"Отображаемое имя",confirmNumber:"Подтвердить",closeEntries:"Закрыть регистрацию",draw:"ПРОВЕСТИ ЖЕРЕБЬЁВКУ",winner:"Выигрышный номер",raffleCreated:"Розыгрыш создан",current:"Текущий",last:"Последний завершённый",noClaims:"Номера ещё не выбраны.",groupMessageTitle:"Готовое сообщение для группы",owner:"Организатор",status:"Статус",disclosure:"Турнир организован пользователем EduCashPro. EduCashPro регистрирует участие и результаты; призы остаются ответственностью организатора."}
  };
  function c(key,l){return COPY[lang(l)]?.[key]||COPY.pt[key]||key}

  function showPaywall(l){suite()?.paywall?.("advanced",l)}

  function openTournament(game, options={}) {
    stopTimers(); const l=lang(options.lang);
    if(!active()) return showPaywall(l);
    content().innerHTML=`<main class="gamePage">${backButton(l)}<section class="hero"><span class="eyebrow">🏆 ${esc(tr("tournament",l))}</span><h1>${esc(c("strategyTitle",l))}</h1><p>${esc(c("strategy",l))}</p></section><section class="socialCard"><h3>💡 ${esc(c("groupHelp",l))}</h3><p>${esc(c("strategyAffiliate",l))}</p><div class="socialActions one"><button id="continueTournament" class="wideButton">${esc(c("continue",l))}</button></div></section></main>`;
    bindBack(); $("#continueTournament").onclick=()=>renderTournamentForm(game,l); window.scrollTo({top:0,behavior:"smooth"});
  }

  function defaultStartValue(){const d=new Date(Date.now()+10*60000);const pad=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
  function renderTournamentForm(game,l){
    content().innerHTML=`<main class="gamePage">${backButton(l)}<section class="hero"><span class="eyebrow">🏆 ${esc(gameName(game,l))}</span><h1>${esc(c("createTitle",l))}</h1><p>${esc(c("strategyAffiliate",l))}</p></section><form id="tournamentForm" class="socialCard socialForm"><label>${esc(c("name",l))}<input id="tName" maxlength="80" required></label><label>${esc(c("difficulty",l))}<select id="tDifficulty"><option value="basic">${esc(tr("basic",l))}</option><option value="medium">${esc(tr("medium",l))}</option><option value="advanced">${esc(tr("advanced",l))}</option><option value="nerd">${esc(tr("nerd",l))}</option></select></label><label>${esc(c("start",l))}<input id="tStart" type="datetime-local" value="${defaultStartValue()}" required></label><label>${esc(c("duration",l))}<select id="tDuration"><option value="15">15 ${esc(c("minutes",l))}</option><option value="30" selected>30 ${esc(c("minutes",l))}</option><option value="60">60 ${esc(c("minutes",l))}</option><option value="120">120 ${esc(c("minutes",l))}</option></select></label><label>${esc(c("winners",l))}<input id="tWinners" type="number" min="1" max="20" value="3"></label><label>${esc(c("rules",l))}<textarea id="tRules" maxlength="1200"></textarea></label><label style="display:flex;grid-template-columns:auto 1fr;align-items:center"><input id="tHide" type="checkbox" checked style="width:20px;min-height:20px">${esc(c("hide",l))}</label><button class="wideButton" id="tSubmit" type="submit">${esc(c("create",l))}</button></form></main>`;
    bindBack(()=>openTournament(game,{lang:l}));
    $("#tournamentForm").onsubmit=async(e)=>{e.preventDefault();const btn=$("#tSubmit"),name=$("#tName").value.trim(),start=$("#tStart").value;if(!name||!start)return;btn.disabled=true;btn.textContent=c("creating",l);try{const data=await api("/api/games/tournaments/create",{name,game,difficulty:$("#tDifficulty").value,startAt:new Date(start).toISOString(),durationMinutes:Number($("#tDuration").value),winnerCount:Number($("#tWinners").value),rules:$("#tRules").value,hideRanking:$("#tHide").checked,organizerName:bridge.session?.profile?.firstName||""});renderTournamentCreated(data.tournament,data.inviteUrl,l);}catch(err){btn.disabled=false;btn.textContent=c("create",l);alert(err?.data?.reason||c("invalid",l));}};
  }

  function tournamentMessages(t,url,l){
    const long={pt:`🏆 TORNEIO EDUCASHPRO\n\nCriei este grupo para reunir os participantes do torneio “${t.name}”.\n\n🎮 Jogo: ${gameName(t.game,l)}\n🕒 Início: ${fmtDate(t.startAt)}\n🎯 Tentativas: 1 por participante\n🏅 Vencedores: ${t.winnerCount}\n\n✅ Participar do torneio é gratuito para os convidados.\n\nQuem quiser aproveitar mais recursos do EduCashPro pode ativar a assinatura e desbloquear níveis avançados, histórico sincronizado, criação dos próprios torneios, modalidades exclusivas e benefícios. O Programa de Afiliados é opcional e não há garantia de ganhos.\n\n👉 Link do torneio: ${url}\n\nFique atento aos avisos do grupo para não perder o horário.`,en:`🏆 EDUCASHPRO TOURNAMENT\n\nTournament: ${t.name}\nGame: ${gameName(t.game,l)}\nStarts: ${fmtDate(t.startAt)}\nOne attempt per participant. Participation is free for invited players.\n\nEduCashPro subscribers unlock advanced levels, synced history, tournament creation and subscriber benefits. Affiliate participation is optional and earnings are not guaranteed.\n\n${url}`,es:`🏆 TORNEO EDUCASHPRO\n\nTorneo: ${t.name}\nJuego: ${gameName(t.game,l)}\nInicio: ${fmtDate(t.startAt)}\nUn intento por participante. Participar es gratis para los invitados.\n\nLos suscriptores desbloquean niveles avanzados, historial sincronizado, creación de torneos y beneficios. El programa de afiliados es opcional y no garantiza ganancias.\n\n${url}`,ru:`🏆 ТУРНИР EDUCASHPRO\n\n${t.name}\nИгра: ${gameName(t.game,l)}\nНачало: ${fmtDate(t.startAt)}\nОдна попытка. Для приглашённых участие бесплатно.\n\nПодписка открывает расширенные уровни, историю, создание турниров и преимущества. Партнёрская программа необязательна и не гарантирует доход.\n\n${url}`}[l]||"";
    const short={pt:`🏆 Nosso torneio “${t.name}” está chegando!\n🎮 ${gameName(t.game,l)} · ${fmtDate(t.startAt)}\nEntre e confirme sua participação: ${url}\n\nA assinatura não é obrigatória para participar deste torneio.`,en:`🏆 “${t.name}” is coming!\n${gameName(t.game,l)} · ${fmtDate(t.startAt)}\nJoin here: ${url}\nSubscription is not required to join this tournament.`,es:`🏆 ¡Se acerca “${t.name}”!\n${gameName(t.game,l)} · ${fmtDate(t.startAt)}\nParticipa aquí: ${url}\nLa suscripción no es obligatoria para este torneo.`,ru:`🏆 Турнир «${t.name}» скоро начнётся!\n${gameName(t.game,l)} · ${fmtDate(t.startAt)}\nУчастие: ${url}\nПодписка для этого турнира не обязательна.`}[l]||"";
    return{long,short};
  }

  function renderTournamentCreated(t,url,l){const msg=tournamentMessages(t,url,l);content().innerHTML=`<main class="gamePage">${backButton(l)}<section class="hero"><span class="eyebrow">${esc(c("created",l))}</span><h1>🏆 ${esc(t.name)}</h1><p>${esc(c("code",l))}: <b>${esc(t.code)}</b></p></section><section class="socialCard"><h3>${esc(c("shareLink",l))}</h3><div class="shareBox">${esc(url)}</div><div id="tQr" class="qrHost" style="margin-top:12px"></div><p>${esc(c("affiliateDisclosure",l))}</p><div class="socialActions"><button id="copyTLink" class="secondaryButton">${esc(c("copyLink",l))}</button><button id="shareTLink" class="secondaryButton">${esc(c("share",l))}</button><button id="copyLong" class="secondaryButton">${esc(c("longMsg",l))}</button><button id="copyShort" class="secondaryButton">${esc(c("shortMsg",l))}</button></div></section><section class="socialCard"><h3>📌 ${esc(c("groupMessageTitle",l))}</h3><p style="white-space:pre-line">${esc(msg.short)}</p><button id="openTRoom" class="wideButton">${esc(c("openRoom",l))}</button></section></main>`;bindBack();qr($("#tQr"),url);$("#copyTLink").onclick=e=>copy(url,e.currentTarget);$("#shareTLink").onclick=()=>shareTelegram(url,msg.short);$("#copyLong").onclick=e=>copy(msg.long,e.currentTarget);$("#copyShort").onclick=e=>copy(msg.short,e.currentTarget);$("#openTRoom").onclick=()=>renderTournamentRoom(t.code,l);}

  async function renderTournamentRoom(code,l,opts={}){stopTimers();content().innerHTML=`<main class="gamePage">${backButton(l)}<div class="empty">•••</div></main>`;bindBack(opts.public?()=>backCatalog():backCatalog);try{const data=await api("/api/games/tournaments/get",{code});currentTournament={...data.tournament,code};renderTournamentData(data,l,opts);}catch(err){content().innerHTML=`<main class="gamePage">${backButton(l)}<div class="empty">${esc(err.message)}</div></main>`;bindBack();}}

  function statusText(status,l){return {registered:c("waiting",l),playing:"🎮",finished:"✅",disqualified:"⛔"}[status]||status}
  function renderTournamentData(data,l,opts){const t=data.tournament,mine=data.mine,now=Date.now(),start=new Date(t.startAt).getTime(),end=new Date(t.deadlineAt).getTime(),canJoin=!mine&&t.status!=="finished"&&now<end,canPlay=mine?.status==="registered"&&now>=start&&now<end,waiting=mine?.status==="registered"&&now<start;
    const winners=(t.winners||[]).map(w=>`<div class="socialRow"><strong>${w.position===1?"🥇":w.position===2?"🥈":w.position===3?"🥉":"#"+w.position} ${esc(w.displayName)}</strong><span>${Number(w.score||0)}</span></div>`).join("");
    const ownerList=t.isOwner&&Array.isArray(t.entries)?`<section class="socialCard"><h3>${esc(c("participants",l))} · ${t.participantCount}</h3><div class="socialList">${t.entries.length?t.entries.map(r=>`<div class="socialRow"><span>${esc(r.displayName)}</span><b>${esc(statusText(r.status,l))}</b></div>`).join(""):`<p>—</p>`}</div></section>`:"";
    content().innerHTML=`<main class="gamePage">${backButton(l)}<section class="hero"><span class="eyebrow">🏆 ${esc(t.code)}</span><h1>${esc(t.name)}</h1><p>${esc(c("owner",l))}: ${esc(t.organizerName)} · ${esc(gameName(t.game,l))} · ${esc(tr(t.difficulty,l))}</p><div class="meta"><span class="chip">🕒 ${esc(fmtDate(t.startAt))}</span><span class="chip">👥 ${t.participantCount}</span><span class="chip">✅ ${t.completedCount}</span></div></section><section class="socialCard"><span class="socialStatus ${t.status==="waiting"?"wait":""}">${esc(t.status)}</span><p><b>${esc(c("oneChance",l))}</b></p>${t.rules?`<p style="white-space:pre-line">${esc(t.rules)}</p>`:""}<p>${esc(c("disclosure",l))}</p><p style="font-size:11px">${esc(t.affiliateDisclosure||c("affiliateDisclosure",l))}</p><div class="socialActions one">${canJoin?`<button id="joinTournament" class="wideButton">${esc(c("join",l))}</button>`:""}${waiting?`<div class="notice"><b>${esc(c("startsIn",l))}: <span id="tCountdown">--:--</span></b></div>`:""}${canPlay?`<button id="startAttempt" class="wideButton">🎮 ${esc(c("playNow",l))}</button>`:""}${mine?.status==="finished"?`<div class="notice">✅ ${esc(c("resultRegistered",l))} · ⭐ ${Number(mine.score||0)}</div>`:""}<button id="refreshTournament" class="secondaryButton">↻ ${esc(c("refresh",l))}</button></div></section>${t.status==="finished"?`<section class="socialCard"><h2>🏆 ${esc(c("official",l))}</h2><div class="socialList">${winners||`<p>${esc(c("noWinners",l))}</p>`}</div></section>`:""}${ownerList}</main>`;
    bindBack();$("#joinTournament")?.addEventListener("click",()=>joinTournament(t.code,l));$("#startAttempt")?.addEventListener("click",()=>startAttempt(t.code,l));$("#refreshTournament")?.addEventListener("click",()=>renderTournamentRoom(t.code,l,opts));if(waiting){const tick=()=>{const left=Math.max(0,start-Date.now()),s=Math.floor(left/1000),m=Math.floor(s/60),sec=s%60;if($("#tCountdown"))$("#tCountdown").textContent=`${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}`;if(left<=0)renderTournamentRoom(t.code,l,opts)};tick();countdownTimer=setInterval(tick,1000);}if(t.status!=="finished"&&!canPlay){lobbyTimer=setInterval(()=>{if(document.visibilityState==="visible")renderTournamentRoom(t.code,l,opts)},15000);}window.scrollTo({top:0,behavior:"smooth"});
  }
  async function joinTournament(code,l){try{await api("/api/games/tournaments/join",{code,displayName:bridge.session?.profile?.firstName||""});renderTournamentRoom(code,l,{public:true});}catch(err){alert(err?.data?.reason||err.message)}}
  async function startAttempt(code,l){stopTimers();try{const data=await api("/api/games/tournaments/start-attempt",{code}),t=currentTournament||{code};suite()?.launchGame?.(data.attempt.game,{lang:l,tournament:{code,attemptId:data.attempt.attemptId,seed:data.attempt.seed,difficulty:data.attempt.difficulty,maxSeconds:data.attempt.maxSeconds}});}catch(err){if(err?.data?.reason==="not_started")return renderTournamentRoom(code,l,{public:true});alert(err?.data?.reason||err.message)}}
  async function submitTournamentResult(ctx,result,proof){const l=lang();content().innerHTML=`<main class="gamePage"><div class="empty">•••</div></main>`;try{const data=await api("/api/games/tournaments/submit",{code:ctx.code,attemptId:ctx.attemptId,result,proof});content().innerHTML=`<main class="gamePage"><section class="hero"><span class="eyebrow">✅ ${esc(c("resultRegistered",l))}</span><h1>⭐ ${Number(data.score||0)}</h1><p>${Math.round(Number(data.durationMs||0)/1000)}s${data.provisionalPosition?` · ${esc(c("provisional",l))}: ${data.provisionalPosition}º`:""}</p></section><button id="backTournament" class="wideButton">🏆 ${esc(c("openRoom",l))}</button></main>`;$("#backTournament").onclick=()=>renderTournamentRoom(ctx.code,l,{public:true});}catch(err){content().innerHTML=`<main class="gamePage"><section class="hero"><h1>⚠️</h1><p>${esc(err?.data?.reason||err.message)}</p></section><button id="retryResult" class="wideButton">${esc(c("refresh",l))}</button></main>`;$("#retryResult").onclick=()=>submitTournamentResult(ctx,result,proof)}}
  function returnToTournament(code){renderTournamentRoom(code,lang(),{public:true})}

  function openRaffle(options={}){const l=lang(options.lang);if(!active())return showPaywall(l);content().innerHTML=`<main class="gamePage">${backButton(l)}<section class="hero"><span class="eyebrow">🎟️ ${esc(tr("raffle",l))}</span><h1>${esc(c("raffleIntro",l))}</h1><p>${esc(c("raffleExplain",l))}</p></section><section class="notice"><b>⚠️</b> ${esc(c("responsibility",l))}</section><form id="raffleForm" class="socialCard socialForm"><label>${esc(c("raffleName",l))}<input id="rName" maxlength="80" required></label><label>${esc(c("numbers",l))}<input id="rCount" type="number" min="2" max="500" value="100"></label><label>${esc(c("description",l))}<textarea id="rDesc" maxlength="600"></textarea></label><label>${esc(c("drawAt",l))}<input id="rDate" type="datetime-local"></label><button class="wideButton" type="submit">${esc(c("createRaffle",l))}</button></form><button id="myRaffles" class="secondaryButton">🎟️ ${esc(c("current",l))} / ${esc(c("last",l))}</button></main>`;bindBack();$("#raffleForm").onsubmit=e=>{e.preventDefault();createRaffle(l)};$("#myRaffles").onclick=()=>listRaffles(l);window.scrollTo({top:0,behavior:"smooth"});}
  async function createRaffle(l){try{const data=await api("/api/games/raffles/create",{name:$("#rName").value,numberCount:Number($("#rCount").value),description:$("#rDesc").value,drawAt:$("#rDate").value?new Date($("#rDate").value).toISOString():null,organizerName:bridge.session?.profile?.firstName||""});renderRaffleCreated(data.raffle,data.inviteUrl,l);}catch(err){if(err?.data?.reason==="active_raffle_exists")return renderRaffle(err.data.code,l,{owner:true});alert(err?.data?.reason||err.message)}}
  function raffleMessage(r,url,l){return {pt:`🎟️ RIFA / SORTEIO ABERTO\n\n${r.name}\nEscolha seu número diretamente pelo link:\n${url}\n\nOs números já escolhidos podem ser acompanhados na própria página. Quando as inscrições forem encerradas, o resultado será divulgado pelo organizador.`,en:`🎟️ NUMBER DRAW\n\n${r.name}\nChoose your number here:\n${url}\n\nChosen numbers are visible on the page.`,es:`🎟️ RIFA / SORTEO\n\n${r.name}\nElige tu número:\n${url}\n\nLos números elegidos se ven en la página.`,ru:`🎟️ РОЗЫГРЫШ\n\n${r.name}\nВыберите номер:\n${url}`}[l]||""}
  function renderRaffleCreated(r,url,l){const msg=raffleMessage(r,url,l);content().innerHTML=`<main class="gamePage">${backButton(l)}<section class="hero"><span class="eyebrow">${esc(c("raffleCreated",l))}</span><h1>🎟️ ${esc(r.name)}</h1><p>${esc(c("code",l))}: ${esc(r.code)}</p></section><section class="socialCard"><div class="shareBox">${esc(url)}</div><div id="rQr" class="qrHost" style="margin-top:12px"></div><div class="socialActions"><button id="copyR" class="secondaryButton">${esc(c("copyLink",l))}</button><button id="shareR" class="secondaryButton">${esc(c("share",l))}</button></div><p style="white-space:pre-line">${esc(msg)}</p><button id="manageR" class="wideButton">${esc(c("openRoom",l))}</button></section></main>`;bindBack();qr($("#rQr"),url);$("#copyR").onclick=e=>copy(url,e.currentTarget);$("#shareR").onclick=()=>shareTelegram(url,msg);$("#manageR").onclick=()=>renderRaffle(r.code,l,{owner:true});}
  async function listRaffles(l){content().innerHTML=`<main class="gamePage">${backButton(l)}<div id="raffleList" class="cardList"><div class="empty">•••</div></div></main>`;bindBack(()=>openRaffle({lang:l}));try{const data=await api("/api/games/raffles/list-owner",{});$("#raffleList").innerHTML=data.items?.length?data.items.map(r=>`<button class="quickCard" data-r-code="${esc(r.code)}"><span class="emoji">🎟️</span><strong>${esc(r.name)}</strong><small>${esc(r.status)} · ${esc(r.code)}</small></button>`).join(""):`<div class="empty">—</div>`;document.querySelectorAll("[data-r-code]").forEach(b=>b.onclick=()=>renderRaffle(b.dataset.rCode,l,{owner:true}));}catch{$("#raffleList").innerHTML=`<div class="empty">—</div>`}}
  async function renderRaffle(code,l,opts={}){selectedRaffleNumber=null;content().innerHTML=`<main class="gamePage">${backButton(l)}<div class="empty">•••</div></main>`;bindBack();try{const data=await api("/api/games/raffles/get",{code}),r=data.raffle,claimed=data.claimed||[],byNum=new Map(claimed.map(x=>[Number(x.number),x]));content().innerHTML=`<main class="gamePage">${backButton(l)}<section class="hero"><span class="eyebrow">🎟️ ${esc(r.code)}</span><h1>${esc(r.name)}</h1><p>${esc(r.description||"")}</p><div class="meta"><span class="chip">${esc(c("owner",l))}: ${esc(r.organizerName)}</span><span class="chip">${esc(c("status",l))}: ${esc(r.status)}</span></div></section>${r.status==="drawn"?`<section class="socialCard" style="text-align:center"><h2>🏆 ${esc(c("winner",l))}</h2><div style="font-size:54px;font-weight:950">${Number(r.winner?.number||0)}</div><p>${esc(r.winner?.displayName||"")}</p></section>`:""}<section class="socialCard"><h3>${esc(c("choose",l))}</h3><div class="raffleNumbers">${Array.from({length:r.numberCount},(_,i)=>{const n=i+1,row=byNum.get(n);return `<button class="raffleNumber ${row?"taken":""}" data-rnum="${n}" ${row||r.status!=="open"?"disabled":""}>${row?`${String(n).padStart(2,"0")}<br>${esc(row.displayName)}`:String(n).padStart(2,"0")}</button>`}).join("")}</div>${r.status==="open"?`<form id="claimForm" class="socialForm" style="margin-top:13px"><label>${esc(c("displayName",l))}<input id="claimName" maxlength="50" value="${esc(bridge.session?.profile?.firstName||"")}"></label><button class="wideButton" type="submit">${esc(c("confirmNumber",l))}</button></form>`:""}</section>${r.isOwner?`<section class="socialCard"><h3>👤 ${esc(c("owner",l))}</h3><div class="socialActions one">${r.status==="open"?`<button id="closeRaffle" class="secondaryButton">${esc(c("closeEntries",l))}</button>`:""}${r.status==="closed"?`<button id="drawRaffle" class="wideButton">🎲 ${esc(c("draw",l))}</button>`:""}<button id="refreshRaffle" class="secondaryButton">↻ ${esc(c("refresh",l))}</button></div></section>`:""}<p class="notice">⚠️ ${esc(c("responsibility",l))}</p></main>`;bindBack();document.querySelectorAll("[data-rnum]").forEach(b=>b.onclick=()=>{selectedRaffleNumber=Number(b.dataset.rnum);document.querySelectorAll("[data-rnum]").forEach(x=>x.classList.toggle("selected",x===b))});$("#claimForm")?.addEventListener("submit",e=>{e.preventDefault();claimRaffle(code,l)});$("#closeRaffle")?.addEventListener("click",()=>closeRaffle(code,l));$("#drawRaffle")?.addEventListener("click",()=>drawRaffle(code,l));$("#refreshRaffle")?.addEventListener("click",()=>renderRaffle(code,l,opts));window.scrollTo({top:0,behavior:"smooth"});}catch(err){alert(err?.data?.reason||err.message)}}
  async function claimRaffle(code,l){if(!selectedRaffleNumber)return;try{await api("/api/games/raffles/claim",{code,number:selectedRaffleNumber,displayName:$("#claimName").value});renderRaffle(code,l,{public:true})}catch(err){alert(err?.data?.reason||err.message);renderRaffle(code,l,{public:true})}}
  async function closeRaffle(code,l){try{await api("/api/games/raffles/close",{code});renderRaffle(code,l,{owner:true})}catch(err){alert(err?.data?.reason||err.message)}}
  async function drawRaffle(code,l){try{const data=await api("/api/games/raffles/draw",{code});renderRaffle(code,l,{owner:true})}catch(err){alert(err?.data?.reason||err.message)}}

  function socialStartParam(params){const tg=window.Telegram?.WebApp,start=String(tg?.initDataUnsafe?.start_param||params?.get?.("tgWebAppStartParam")||"");const directT=String(params?.get?.("tournament")||""),directR=String(params?.get?.("raffle")||"");if(directT)return{type:"tournament",code:directT};if(directR)return{type:"raffle",code:directR};if(start.startsWith("tournament_"))return{type:"tournament",code:start.slice(11)};if(start.startsWith("raffle_"))return{type:"raffle",code:start.slice(7)};return null}
  const previousBoot=base.bootPublic?.bind(base);
  base.bootPublic=async function(params){const social=socialStartParam(params);if(social&&bridge.session?.token){if(social.type==="tournament")renderTournamentRoom(social.code,lang(params?.get?.("lang")),{public:true});else renderRaffle(social.code,lang(params?.get?.("lang")),{public:true});return true}return previousBoot?previousBoot(params):false};

  window.EduCashProSocial={openTournament,openRaffle,renderTournamentRoom,renderRaffle,submitTournamentResult,returnToTournament};
})();
