(function(){
  const tg=window.Telegram?.WebApp, params=new URL(location.href).searchParams;
  const API_BASE=/^https:\/\//i.test(params.get("api")||"")?params.get("api").replace(/\/+$/,""):"https://educashpro-all.onrender.com";
  const content=document.getElementById("content"),toast=document.getElementById("toast");
  let token="",lang="pt",isAdmin=false,items=[];
  const C={
    pt:{subtitle:"Fale com o administrador",title:"Central de mensagens",lead:"Envie um relato privado. Somente o administrador poderá visualizar.",category:"Assunto",problem:"Relatar problema",failure:"Relatar falha",suggestion:"Enviar sugestão",message:"Mensagem",placeholder:"Explique com detalhes para facilitar a análise.",send:"Enviar ao administrador",sent:"Mensagem enviada.",mine:"Minhas mensagens",adminTitle:"Mensagens dos usuários",open:"Aguardando resposta",replied:"Respondida",reply:"Responder",replyPlaceholder:"Digite a resposta ao usuário",delete:"Excluir",confirmDelete:"Excluir definitivamente esta mensagem?",empty:"Nenhuma mensagem.",error:"Não foi possível concluir.",retry:"Tentar novamente",tooShort:"Escreva pelo menos 10 caracteres.",rate:"Aguarde um minuto antes de enviar outra mensagem.",back:"Voltar"},
    en:{subtitle:"Contact the administrator",title:"Message center",lead:"Send a private report. Only the administrator can view it.",category:"Subject",problem:"Report a problem",failure:"Report a failure",suggestion:"Send a suggestion",message:"Message",placeholder:"Describe the details to help with the review.",send:"Send to administrator",sent:"Message sent.",mine:"My messages",adminTitle:"User messages",open:"Waiting for reply",replied:"Replied",reply:"Reply",replyPlaceholder:"Enter the reply to the user",delete:"Delete",confirmDelete:"Permanently delete this message?",empty:"No messages.",error:"Could not complete.",retry:"Try again",tooShort:"Write at least 10 characters.",rate:"Wait one minute before sending another message.",back:"Back"},
    es:{subtitle:"Hablar con el administrador",title:"Central de mensajes",lead:"Envía un informe privado. Solo el administrador podrá verlo.",category:"Asunto",problem:"Informar problema",failure:"Informar falla",suggestion:"Enviar sugerencia",message:"Mensaje",placeholder:"Explica los detalles para facilitar el análisis.",send:"Enviar al administrador",sent:"Mensaje enviado.",mine:"Mis mensajes",adminTitle:"Mensajes de usuarios",open:"Esperando respuesta",replied:"Respondida",reply:"Responder",replyPlaceholder:"Escribe la respuesta al usuario",delete:"Eliminar",confirmDelete:"¿Eliminar definitivamente este mensaje?",empty:"No hay mensajes.",error:"No fue posible completar.",retry:"Intentar nuevamente",tooShort:"Escribe al menos 10 caracteres.",rate:"Espera un minuto antes de enviar otro mensaje.",back:"Volver"},
    ru:{subtitle:"Связаться с администратором",title:"Центр сообщений",lead:"Отправьте личное обращение. Его увидит только администратор.",category:"Тема",problem:"Сообщить о проблеме",failure:"Сообщить об ошибке",suggestion:"Отправить предложение",message:"Сообщение",placeholder:"Опишите подробности, чтобы облегчить проверку.",send:"Отправить администратору",sent:"Сообщение отправлено.",mine:"Мои сообщения",adminTitle:"Сообщения пользователей",open:"Ожидает ответа",replied:"Получен ответ",reply:"Ответить",replyPlaceholder:"Введите ответ пользователю",delete:"Удалить",confirmDelete:"Удалить это сообщение навсегда?",empty:"Нет сообщений.",error:"Не удалось выполнить.",retry:"Повторить",tooShort:"Введите не менее 10 символов.",rate:"Подождите минуту перед отправкой нового сообщения.",back:"Назад"}
  };
  const t=k=>C[lang]?.[k]||C.pt[k]||k, esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const show=m=>{toast.textContent=m;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2300)};
  async function api(path,payload={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(`${API_BASE}${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload),cache:"no-store",signal:controller.signal});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.reason||"error");e.reason=d.reason;throw e}return d}finally{clearTimeout(timer)}}
  const date=v=>new Date(v).toLocaleString(lang==="pt"?"pt-BR":lang,{dateStyle:"short",timeStyle:"short"});
  function categoryLabel(v){return t(v==="problem"?"problem":v==="failure"?"failure":"suggestion")}
  function render(){
    document.getElementById("subtitle").textContent=t("subtitle");
    const form=isAdmin?"":`<section class="card"><h1>${esc(t("title"))}</h1><p>${esc(t("lead"))}</p><label>${esc(t("category"))}<select id="category"><option value="problem">${esc(t("problem"))}</option><option value="failure">${esc(t("failure"))}</option><option value="suggestion">${esc(t("suggestion"))}</option></select></label><label>${esc(t("message"))}<textarea id="message" maxlength="1500" rows="7" placeholder="${esc(t("placeholder"))}"></textarea></label><button id="send" class="primary">${esc(t("send"))}</button></section>`;
    const cards=items.length?items.map(item=>`<article class="messageCard"><div class="meta"><span>${esc(categoryLabel(item.category))}</span><span class="${item.status}">${esc(t(item.status))}</span></div>${isAdmin?`<p class="user"><b>${esc(item.user.name||item.user.tgId)}</b> ${item.user.username?`@${esc(item.user.username)}`:""} · <code>${esc(item.user.tgId)}</code></p>`:""}<p class="body">${esc(item.message)}</p><small>${esc(date(item.createdAt))}</small>${item.reply?`<div class="answer"><b>${esc(t("reply"))}</b><p>${esc(item.reply)}</p></div>`:""}${isAdmin?`<textarea data-reply="${item.id}" rows="3" maxlength="1500" placeholder="${esc(t("replyPlaceholder"))}"></textarea><div class="actions"><button data-send-reply="${item.id}" class="primary">${esc(t("reply"))}</button><button data-delete="${item.id}" class="danger">${esc(t("delete"))}</button></div>`:""}</article>`).join(""):`<div class="empty">${esc(t("empty"))}</div>`;
    content.innerHTML=form+`<section><h2>${esc(t(isAdmin?"adminTitle":"mine"))}</h2><div class="list">${cards}</div></section>`;
    document.getElementById("send")?.addEventListener("click",send);
    content.querySelectorAll("[data-send-reply]").forEach(b=>b.onclick=()=>reply(b.dataset.sendReply));
    content.querySelectorAll("[data-delete]").forEach(b=>b.onclick=()=>remove(b.dataset.delete));
  }
  async function load(){try{const d=await api("/api/support/bootstrap",{token});isAdmin=!!d.isAdmin;items=d.items||[];render()}catch{content.innerHTML=`<div class="empty">${esc(t("error"))}<button id="retry" class="primary">${esc(t("retry"))}</button></div>`;document.getElementById("retry").onclick=load}}
  async function send(){const message=document.getElementById("message").value.trim(),category=document.getElementById("category").value;if(message.length<10)return show(t("tooShort"));const button=document.getElementById("send");button.disabled=true;try{const d=await api("/api/support/submit",{token,category,message});items.unshift(d.item);render();show(t("sent"))}catch(e){show(e.reason==="rate_limited"?t("rate"):t("error"));button.disabled=false}}
  async function reply(id){const field=document.querySelector(`[data-reply="${id}"]`),value=field.value.trim();if(value.length<2)return;try{await api("/api/support/admin/reply",{token,id,reply:value});await load()}catch{show(t("error"))}}
  async function remove(id){if(!confirm(t("confirmDelete")))return;try{await api("/api/support/admin/delete",{token,id});items=items.filter(x=>x.id!==id);render()}catch{show(t("error"))}}
  async function init(){tg?.ready?.();tg?.expand?.();document.getElementById("close").onclick=()=>tg?.close?.();document.getElementById("back").onclick=()=>history.length>1?history.back():location.assign("./");if(!tg?.initData)return content.innerHTML=`<div class="empty">${esc(t("error"))}</div>`;try{const s=await api("/api/hub/session",{initData:tg.initData});token=s.token;lang=["pt","en","es","ru"].includes(s.profile?.language)?s.profile.language:"pt";document.documentElement.lang=lang;await load()}catch{content.innerHTML=`<div class="empty">${esc(t("error"))}</div>`}}
  document.addEventListener("DOMContentLoaded",init);
})();